add support to set LANG

diff --git a/usr/bin/myapp b/usr/bin/myapp
--- a/usr/bin/myapp
+++ b/usr/bin/myapp
@@ -2,7 +2,7 @@
 
 # AppRun Script version
 # date -u +%s
-MYAPPRUN_VERSION=1645051236
+MYAPPRUN_VERSION=1645265363
 
 #############################################
 ## prevent running by root/sudo
@@ -156,7 +156,7 @@ run option:
 	walkthrough. for example, "--browser=firefox"
 	means using firefox to open walkthrough.html
 
-  --portable-cache
+  -p, --portable-cache
 	create \${APPIMAGE}.cache directory then exit.
 	when running appimage, \$HOME and \$XDG_CONFIG_HOME
 	will be redirect to this directory to prevent
@@ -176,10 +176,14 @@ test option:
 	use this option to test or install windows application.
 	when this option set, -s and -w will be ignored.
 
-  --exeinfo-gen[=gui|cli]
+  --exeinfo-gen [=gui|cli|zenity|kdialog]
+		=gui :automatically find zenity or kdialog to run
+		=cli :(only apply when launch from command line)
+		=zenity :use zenity to run
+		=kdialog :use kdialog to run
 	after install windows application in AppDir,
-	run ./AppRun with this option to generate
-	exeinfo_profile.
+	run "./AppRun --exeinfo-gen" to generate
+	exeinfo_profile. default is "gui"
 
 
 appimage option:
@@ -231,12 +235,15 @@ EOF
 parameters=$(echo "$@"|tr "=" " ")
 eval set -- "$parameters"
 
-function is_option(){
-	if [[ ${1::1} == "-" ]];
+function option_check(){
+	if [[ ${1::2} == "--" ]];
 	then
-		return 0
+		echo "long"
+	elif [[ ${1::1} == "-" ]];
+	then
+		echo "short"
 	else
-		return 1
+		echo "non"
 	fi
 }
 
@@ -256,7 +263,7 @@ while [[ -n "$1" ]] ; do
 			shift ;;
 		--browser)
 			#i3-sensible-browser will choose $BROWSER to open walkthrough first
-			is_option "$2" && echo "invalid option $1" >&2 && exit 1
+			[[ $(option_check "$2") != "non" ]] && echo "invalid option $1" >&2 && exit 1
 			BROWSER="$2"
 			shift 2;;
 		-t| --test-winetricks)
@@ -264,7 +271,15 @@ while [[ -n "$1" ]] ; do
 			shift ;;
 		--exeinfo-gen)
 			EXEINFO_GEN_FLAG=1
-			if [[ $2 == "gui" ]];
+			if [[ $2 == "zenity" ]];
+			then
+				EXEINFO_GEN_METHOD="zenity"
+				shift 2
+			elif [[ $2 == "kdialog" ]];
+			then
+				EXEINFO_GEN_METHOD="kdialog"
+				shift 2
+			elif [[ $2 == "gui" ]];
 			then
 				EXEINFO_GEN_METHOD="gui"
 				shift 2
@@ -277,7 +292,7 @@ while [[ -n "$1" ]] ; do
 				shift
 			fi
 			;;
-		--portable-cache)
+		-p| --portable-cache)
 			mkdir -p "$APPIMAGE".cache/home/public_user/
 			echo ""
 			echo "created cache directory: $APPIMAGE.cache"
@@ -496,9 +511,9 @@ EOF
 #export LANG=ja_JP.UTF-8
 [[ -n $MYAPPLANG ]] && LANG=$MYAPPLANG || LANG="ja_JP.UTF-8"
 
-if [[ $EXEINFO_GEN_FLAG -eq 1 && $EXEINFO_GEN_METHOD == "gui" ]];
+if [[ $EXEINFO_GEN_FLAG -eq 1 ]];
 then
-	exeinfo_main
+	[[ $EXEINFO_GEN_METHOD == "gui" || $EXEINFO_GEN_METHOD == "zenity" || $EXEINFO_GEN_METHOD == "kdialog" ]] && exeinfo_main
 fi
 
 if [[ ! $EXEINFO_GEN_FLAG -eq 1 ]];
@@ -563,7 +578,7 @@ function monitor_exe_running(){
 	# if return out of this function directly without waiting wine shutdown,
 	# unionfs drive will be unmount immediately.
 	# therefore we can add a "wineboot" command to wait for wine saving the registry.
-	wineboot -s
+	[[ ! $EXEINFO_GEN_FLAG -eq 1 ]] && wineboot -s
 }
 monitor_exe_running
 
diff --git a/usr/bin/myapp-plugin-exeinfo-gen b/usr/bin/myapp-plugin-exeinfo-gen
--- a/usr/bin/myapp-plugin-exeinfo-gen
+++ b/usr/bin/myapp-plugin-exeinfo-gen
@@ -6,16 +6,20 @@ function exeinfo_test_env(){
 	# these env should be passed to this script
 	cat << EOF
 [myapp-exeinfo-plugin-gen]: test env
+required:
 MYAPPDEBUG=$MYAPPDEBUG
 APPDIR=$APPDIR
 APPIMAGE_CACHE_DIR=$APPIMAGE_CACHE_DIR
 EXEINFO_GEN_METHOD=$EXEINFO_GEN_METHOD
+
+optional:
 EXE_LDIR=$EXE_LDIR
 EXE_WROOT=$EXE_WROOT
 EXE_WDIR=$EXE_WDIR
 EXENAME=$EXENAME
 SAVEDATA_IN_HOME=$SAVEDATA_IN_HOME
 SAVEDATA_DIR=$SAVEDATA_DIR
+MYAPPLANG=$MYAPPLANG
 EOF
 }
 ##############################################
@@ -78,34 +82,47 @@ function exeinfo_load_env(){
 	TEMP_EXENAME=$EXENAME
 	TEMP_SAVEDATA_IN_HOME=$SAVEDATA_IN_HOME
 	TEMP_SAVEDATA_DIR=$SAVEDATA_DIR
+	TEMP_MYAPPLANG=$TEMP_MYAPPLANG
 }
 
 function exeinfo_test_gui(){
-	if [[ $EXEINFO_GEN_METHOD == "gui" ]];
+	if [[ $EXEINFO_GEN_METHOD == "kdialog" ]];
+	then
+		[[ $(command -v kdialog) ]] && return || EXIT_MAIN_MENU=1
+	elif [[ $EXEINFO_GEN_METHOD == "zenity" ]];
+	then
+		[[ $(command -v zenity) ]] && return || EXIT_MAIN_MENU=1
+	elif [[ $EXEINFO_GEN_METHOD == "gui" ]];
 	then
 		if [[ $(command -v zenity) ]];
 		then
 			EXEINFO_GEN_METHOD="zenity"
+			return
 		elif [[ $(command -v kdialog) ]];
 		then
 			EXEINFO_GEN_METHOD="kdialog"
+			return
 		else
-			# launch from commandline but fail to find kdialog: go to CLI mode.
-			# launch by double click but fail to find kdialog: exit directly.
-			if [[ -t 0 ]];
-			then
-				echo "kdialog not found, using commandline to read input."
-				EXEINFO_GEN_METHOD="read"
-			else
-				notify-send --app-name "AppRun" --expire-time 15000 "AppRun:plugin-exeinfo error" "kdialog not found, cannot run exeinfo-gen. Please install kdialog. Otherwise you can run in commandline with --exeinfo-gen=cli option to enter exeinfo-gen."
-				EXIT_MAIN_MENU=1
-			fi
+			EXIT_MAIN_MENU=1
 		fi
 	elif [[ $EXEINFO_GEN_METHOD == "cli" ]];
 	then
-		EXEINFO_GEN_METHOD="read"
+		return
 	else
 		echo "unknow option $EXEINFO_GEN_METHOD" >&2
+		EXIT_MAIN_MENU=1
+	fi
+
+	# fallback solution
+	# launch from commandline but fail to find gui: go to CLI mode.
+	# launch by double click but fail to find gui: exit directly.
+	if [[ -t 0 ]];
+	then
+		echo "cannot find $EXEINFO_GEN_METHOD, using commandline to read input."
+		EXEINFO_GEN_METHOD="cli"
+		EXIT_MAIN_MENU=0
+	else
+		notify-send --app-name "AppRun" --expire-time 15000 "AppRun:plugin-exeinfo error" "$EXEINFO_GEN_METHOD not found, cannot run exeinfo-gen. Please install [kdialog] or [zenity]. Otherwise you can run in commandline with --exeinfo-gen=cli option to enter exeinfo-gen."
 		EXIT_MAIN_MENU=1
 	fi
 
@@ -117,13 +134,14 @@ function exeinfo_main_menu(){
 		MENU_SELECT_ITEM=$(kdialog --geometry 1000x600 --title "exe info setting" --menu "select one of items to go" \
 			1 "1. set exe file location($TEMP_EXENAME)" \
 			2 "2. set savedata directory location($TEMP_SAVEDATA_DIR)" \
-			3 "3. ***write into exeinfo_profile" \
-			4 "4. ***cancel and exit without saving into exeinfo_profile" \
+			3 "3. set \$LANG for this game($TEMP_MYAPPLANG)" \
+			4 "4. ***write into exeinfo_profile" \
+			5 "5. ***cancel and exit without saving into exeinfo_profile" \
 			--ok-label "go" --cancel-label "close")
 		# result:
-		# $? return 0: click ok, also echo item tag(1/2/3/4)
+		# $? return 0: click ok, also echo item tag(1/2/3/4/5)
 		# $? return 1: click cancel
-		[[ $? -eq 1 ]] && MENU_SELECT_ITEM=4
+		[[ $? -eq 1 ]] && MENU_SELECT_ITEM=5
 	elif [[ $EXEINFO_GEN_METHOD == "zenity" ]];
 	then
 		MENU_SELECT_ITEM=$(zenity --width=1000 --height=600 --list --title="exe info setting" \
@@ -132,30 +150,33 @@ function exeinfo_main_menu(){
 			--column="item" --column="action" \
 			"1" "set exe file location($TEMP_EXENAME)" \
 			"2" "set savedata directory location($TEMP_SAVEDATA_DIR)" \
-			"3" "***write into exeinfo_profile" \
-			"4" "***cancel and exit without saving into exeinfo_profile")
+			"3" "set \$LANG for this game($TEMP_MYAPPLANG)" \
+			"4" "***write into exeinfo_profile" \
+			"5" "***cancel and exit without saving into exeinfo_profile")
 		# result:
-		# $? return 0: click ok, also echo item tag(1/2/3/4)
+		# $? return 0: click ok, also echo item tag(1/2/3/4/5)
 		# $? return 1: click cancel
-		[[ $? -eq 1 ]] && MENU_SELECT_ITEM=4
-	elif [[ $EXEINFO_GEN_METHOD == "read" ]];
+		[[ $? -eq 1 ]] && MENU_SELECT_ITEM=5
+	elif [[ $EXEINFO_GEN_METHOD == "cli" ]];
 	then
 		while true; do
 			cat << EOF
 ##################################################
   current EXENAME=$TEMP_EXENAME
   current SAVEDATA_DIR=$TEMP_SAVEDATA_DIR
+  current MYAPPLANG=$TEMP_MYAPPLANG
 ##################################################
   please select one of below items:
   1. set .exe file location
   2. set savedata directory location
-  3. ***write into exeinfo_profile
-  4. ***cancel and exit without saving into exeinfo_profile
+  3. set \$LANG for this game
+  4. ***write into exeinfo_profile then exit
+  5. ***cancel and exit without saving into exeinfo_profile
 ##################################################
 EOF
-			read -p "select item (1/2/3/4):" MENU_SELECT_ITEM
+			read -p "select item (1/2/3/4/5):" MENU_SELECT_ITEM
 			case "$MENU_SELECT_ITEM" in
-				1| 2| 3| 4)
+				1| 2| 3| 4| 5)
 					break
 					;;
 				*)
@@ -170,11 +191,11 @@ EOF
 function exeinfo_exe_location(){
 	if [[ $EXEINFO_GEN_METHOD == "kdialog" ]];
 	then
-		TEMP_EXEPATH="$(kdialog --geometry 1000x600 --title "select the .exe file" --getopenfilename "$APPIMAGE_CACHE_DIR")"
+		TEMP_EXEPATH="$(kdialog --geometry 1000x600 --title "select the .exe file" --getopenfilename "$APPIMAGE_CACHE_DIR/usr/share"/* )"
 		RETURN_STATUS="$?"
 	elif [[ $EXEINFO_GEN_METHOD == "zenity" ]];
 	then
-		TEMP_EXEPATH="$(zenity --width=1000 --height=600 --file-selection --title="select the .exe file" --filename="$APPIMAGE_CACHE_DIR")"
+		TEMP_EXEPATH="$(zenity --width=1000 --height=600 --file-selection --title="select the .exe file" --filename="$APPIMAGE_CACHE_DIR/usr/share"/* )"
 		RETURN_STATUS="$?"
 	else
 		clear
@@ -192,7 +213,11 @@ function exeinfo_exe_location(){
 		read -e -p "input .exe file path: " -i "$APPIMAGE_CACHE_DIR" TEMP_EXEPATH
 		RETURN_STATUS="$?"
 		TEMP_EXEPATH="$(readlink -f "$TEMP_EXEPATH")"
-		if [[ ! -f "$TEMP_EXEPATH" ]];
+		if [[ -z "$TEMP_EXEPATH" ]];
+		then
+			clear
+			return
+		elif [[ ! -f "$TEMP_EXEPATH" ]];
 		then
 			clear
 			echo "########################################"
@@ -204,7 +229,9 @@ function exeinfo_exe_location(){
 		fi
 	fi
 
-	if [[ $RETURN_STATUS -eq 0 ]];	# clicked "ok"
+	clear
+	# if clicked "ok"
+	if [[ $RETURN_STATUS -eq 0 && -n $TEMP_EXEPATH ]];
 	then
 		# check if .exe file in appdir or in appdir.cache
 		if [[ "${TEMP_EXEPATH#"$APPIMAGE_CACHE_DIR/usr/share"}" != "$TEMP_EXEPATH" ]];
@@ -256,18 +283,17 @@ function exeinfo_exe_location(){
 	unset TEMP_EXEPATH
 	unset TEMP_EXE_LROOT
 	unset RETURN_STATUS
-	clear
 }
 
 
 function exeinfo_savedata_location(){
 	if [[ $EXEINFO_GEN_METHOD == "kdialog" ]];
 	then
-		TEMP_SAVEDATAPATH=$(kdialog --geometry 1000x600 --title "select the directory where to save the savedata files" --getexistingdirectory "$APPIMAGE_CACHE_DIR")
+		TEMP_SAVEDATAPATH=$(kdialog --geometry 1000x600 --title "select the directory where to save the savedata files" --getexistingdirectory "$APPIMAGE_CACHE_DIR/usr/share"/* )
 		RETURN_STATUS="$?"
 	elif [[ $EXEINFO_GEN_METHOD == "zenity" ]];
 	then
-		TEMP_SAVEDATAPATH="$(zenity --width=1000 --height=600 --file-selection --directory --title="select the directory where to save the savedata files" --filename="$APPIMAGE_CACHE_DIR")"
+		TEMP_SAVEDATAPATH="$(zenity --width=1000 --height=600 --file-selection --directory --title="select the directory where to save the savedata files" --filename="$APPIMAGE_CACHE_DIR/usr/share"/* )"
 		RETURN_STATUS="$?"
 	else
 		clear
@@ -300,7 +326,7 @@ function exeinfo_savedata_location(){
 	fi
 
 	clear
-	if [[ $RETURN_STATUS -eq 0 ]];
+	if [[ $RETURN_STATUS -eq 0 && -n $TEMP_SAVEDATAPATH ]];
 	then
 		if [[ "${TEMP_SAVEDATAPATH#"${APPIMAGE_CACHE_DIR}/usr/share"}" != "$TEMP_SAVEDATAPATH" ]];
 		then
@@ -332,6 +358,74 @@ function exeinfo_savedata_location(){
 	unset TEMP_SAVEDATAPATH
 }
 
+function exeinfo_locale(){
+	if [[ $EXEINFO_GEN_METHOD == "kdialog" ]];
+	then
+		TEMP_MYAPPLANG=$(kdialog --geometry 1000x600 --inputbox \
+"set \$LANG for this game:
+supported locale in current system:
+
+$(localectl list-locales)
+
+you can only choose one of above items to setup.
+because if you cannot find your language in this list,
+that means you cannot use this language setting to run this game.
+if you cannot find your language in this list,
+please use locale-gen to generate locale setting first." "$LANG")
+		RETURN_STATUS="$?"
+	elif [[ $EXEINFO_GEN_METHOD == "zenity" ]];
+	then
+		# TODO: zenity --text option ignore underscore"_" output. I used whitespace" " to replace underscore"_" at this moment.
+		TEMP_MYAPPLANG=$(zenity --entry --text=\
+" \
+set \$LANG for this game:\n \
+supported locale in current system:\n \
+\n\
+$(localectl list-locales| sed -e 's/_/ /')
+\n \
+you can only choose one of above items to setup.\n \
+because if you cannot find your language in this list,\n \
+that means you cannot use this language setting to run this game.\n \
+if you cannot find your language in this list,\n \
+please use locale-gen to generate locale setting first.\n" --entry-text="$LANG")
+		RETURN_STATUS=$?
+	else
+		clear
+		echo "  to go back to previous menu, please <backspace> to earse all words then push <enter>"
+		echo ""
+		echo ""
+		echo "##################################################"
+		echo "  set \$LANG for this game:"
+		echo "  supported locale in current system:"
+		echo ""
+		localectl list-locales
+		echo ""
+		echo "  you can only choose one of above items to setup."
+		echo "  because if you cannot find your language in this list,"
+		echo "  that means you cannot use this language setting to run this game."
+		echo "  if you cannot find your language in this list,"
+		echo "  please use locale-gen to generate locale setting first."
+		echo "##################################################"
+		echo ""
+		read -p "set MYAPPLANG=: " -i "$LANG" TEMP_MYAPPLANG
+		RETURN_STATUS="$?"
+	fi
+
+	clear
+	if [[ $RETURN_STATUS -eq 0 && -n $TEMP_MYAPPLANG ]];
+	then
+		if ! (localectl list-locales| grep "$TEMP_MYAPPLANG" -x --quiet 2>/dev/null );
+		then
+			echo "########################################"
+			echo "ERROR: unsupport MYAPPLANG: $TEMP_MYAPPLANG"
+			echo "########################################"
+			echo ""
+			unset TEMP_MYAPPLANG
+		fi
+	fi
+	unset RETURN_STATUS
+}
+
 function exeinfo_write_file(){
 	if [[ $EXEINFO_GEN_METHOD == "kdialog" ]];
 	then
@@ -343,6 +437,7 @@ EXE_WDIR=\"$EXE_WDIR\"
 EXENAME=\"$EXENAME\"
 SAVEDATA_IN_HOME=\"$SAVEDATA_IN_HOME\"
 SAVEDATA_DIR=\"$SAVEDATA_DIR\"
+MYAPPLANG=\"$MYAPPLANG\"
 
 new:
 EXE_LDIR=\"$TEMP_EXE_LDIR\"
@@ -351,6 +446,7 @@ EXE_WDIR=\"$TEMP_EXE_WDIR\"
 EXENAME=\"$TEMP_EXENAME\"
 SAVEDATA_IN_HOME=\"$TEMP_SAVEDATA_IN_HOME\"
 SAVEDATA_DIR=\"$TEMP_SAVEDATA_DIR\"
+MYAPPLANG=\"$TEMP_MYAPPLANG\"
 
 write into exeinfo_profile?
 "
@@ -366,6 +462,7 @@ EXE_WDIR=\"$EXE_WDIR\"\n \
 EXENAME=\"$EXENAME\"\n \
 SAVEDATA_IN_HOME=\"$SAVEDATA_IN_HOME\"\n \
 SAVEDATA_DIR=\"$SAVEDATA_DIR\"\n \
+MYAPPLANG=\"$MYAPPLANG\"\n \
 \n \
 new:\n \
 EXE_LDIR=\"$TEMP_EXE_LDIR\"\n \
@@ -374,10 +471,11 @@ EXE_WDIR=\"$TEMP_EXE_WDIR\"\n \
 EXENAME=\"$TEMP_EXENAME\"\n \
 SAVEDATA_IN_HOME=\"$TEMP_SAVEDATA_IN_HOME\"\n \
 SAVEDATA_DIR=\"$TEMP_SAVEDATA_DIR\"\n \
+MYAPPLANG=\"$TEMP_MYAPPLANG\"\n \
 \n \
 write into exeinfo_profile?\n"
 		RETURN_NUMBER=$?
-	elif [[ $EXEINFO_GEN_METHOD == "read" ]];
+	elif [[ $EXEINFO_GEN_METHOD == "cli" ]];
 	then
 		while true; do
 			clear
@@ -431,8 +529,11 @@ EXE_WDIR="$TEMP_EXE_WDIR"
 EXENAME="$TEMP_EXENAME"
 SAVEDATA_IN_HOME="$TEMP_SAVEDATA_IN_HOME"
 SAVEDATA_DIR="$TEMP_SAVEDATA_DIR"
+MYAPPLANG="$TEMP_MYAPPLANG"
 EOF
 	echo "saved into $APPIMAGE_CACHE_DIR/usr/share/exeinfo_profile"
+	cat "$APPIMAGE_CACHE_DIR/usr/share/exeinfo_profile" > "$APPIMAGE_CACHE_DIR/usr/share/exeinfo_profile.$TEMP_MYAPPLANG"
+	echo "saved into $APPIMAGE_CACHE_DIR/usr/share/exeinfo_profile.$TEMP_MYAPPLANG"
 	EXIT_MAIN_MENU=1
 
 }
@@ -446,7 +547,7 @@ function exeinfo_confirm_exit(){
 	then
 		zenity --question --text="exit exeinfo setting?"
 		RETURN_NUMBER=$?
-	elif [[ "$EXEINFO_GEN_METHOD" == "read" ]];
+	elif [[ "$EXEINFO_GEN_METHOD" == "cli" ]];
 	then
 		while true; do
 			read -p "exit exeinfo setting?(y/n): " RETURN_NUMBER
@@ -496,8 +597,11 @@ function exeinfo_main(){
 			exeinfo_savedata_location
 		elif [[ $MENU_SELECT_ITEM -eq 3 ]];
 		then
-			exeinfo_write_file
+			exeinfo_locale
 		elif [[ $MENU_SELECT_ITEM -eq 4 ]];
+		then
+			exeinfo_write_file
+		elif [[ $MENU_SELECT_ITEM -eq 5 ]];
 		then
 			exeinfo_confirm_exit
 		else
