add zenity support

diff --git a/usr/bin/myapp-plugin-exeinfo-gen b/usr/bin/myapp-plugin-exeinfo-gen
--- a/usr/bin/myapp-plugin-exeinfo-gen
+++ b/usr/bin/myapp-plugin-exeinfo-gen
@@ -1,5 +1,26 @@
 #!/bin/bash
 
+##############################################
+## test env
+function exeinfo_test_env(){
+	# these env should be passed to this script
+	cat << EOF
+[myapp-exeinfo-plugin-gen]: test env
+MYAPPDEBUG=$MYAPPDEBUG
+APPDIR=$APPDIR
+APPIMAGE_CACHE_DIR=$APPIMAGE_CACHE_DIR
+EXEINFO_GEN_METHOD=$EXEINFO_GEN_METHOD
+EXE_LDIR=$EXE_LDIR
+EXE_WROOT=$EXE_WROOT
+EXE_WDIR=$EXE_WDIR
+EXENAME=$EXENAME
+SAVEDATA_IN_HOME=$SAVEDATA_IN_HOME
+SAVEDATA_DIR=$SAVEDATA_DIR
+EOF
+}
+##############################################
+
+
 
 ##############################################
 function apprun_realpath(){
@@ -50,7 +71,7 @@ function apprun_realpath(){
 
 }
 
-function temp_exeinfo(){
+function exeinfo_load_env(){
 	TEMP_EXE_LDIR=$EXE_LDIR
 	TEMP_EXE_WROOT=$EXE_WROOT
 	TEMP_EXE_WDIR=$EXE_WDIR
@@ -59,15 +80,26 @@ function temp_exeinfo(){
 	TEMP_SAVEDATA_DIR=$SAVEDATA_DIR
 }
 
-function test_gui(){
+function exeinfo_test_gui(){
 	if [[ $EXEINFO_GEN_METHOD == "gui" ]];
 	then
-		if [[ $(command -v kdialog) ]];
+		if [[ $(command -v zenity) ]];
+		then
+			EXEINFO_GEN_METHOD="zenity"
+		elif [[ $(command -v kdialog) ]];
 		then
 			EXEINFO_GEN_METHOD="kdialog"
 		else
-			echo "kdialog not found, using commandline to read input."
-			EXEINFO_GEN_METHOD="read"
+			# launch from commandline but fail to find kdialog: go to CLI mode.
+			# launch by double click but fail to find kdialog: exit directly.
+			if [[ -t 0 ]];
+			then
+				echo "kdialog not found, using commandline to read input."
+				EXEINFO_GEN_METHOD="read"
+			else
+				notify-send --app-name "AppRun" --expire-time 15000 "AppRun:plugin-exeinfo error" "kdialog not found, cannot run exeinfo-gen. Please install kdialog. Otherwise you can run in commandline with --exeinfo-gen=cli option to enter exeinfo-gen."
+				EXIT_MAIN_MENU=1
+			fi
 		fi
 	elif [[ $EXEINFO_GEN_METHOD == "cli" ]];
 	then
@@ -82,12 +114,30 @@ function test_gui(){
 function exeinfo_main_menu(){
 	if [[ $EXEINFO_GEN_METHOD == "kdialog" ]];
 	then
-		MENU_SELECT_ITEM=$(kdialog --geometry 1000x600 --title "exe info setting" --menu "select one of items to go" 1 "1. set exe file location($TEMP_EXENAME)" 2 "2. set savedata directory location($TEMP_SAVEDATA_DIR)" 3 "3. ***write into exeinfo_profile" 4 "4. ***cancel and exit without saving into exeinfo_profile" --ok-label "go" --cancel-label "close")
+		MENU_SELECT_ITEM=$(kdialog --geometry 1000x600 --title "exe info setting" --menu "select one of items to go" \
+			1 "1. set exe file location($TEMP_EXENAME)" \
+			2 "2. set savedata directory location($TEMP_SAVEDATA_DIR)" \
+			3 "3. ***write into exeinfo_profile" \
+			4 "4. ***cancel and exit without saving into exeinfo_profile" \
+			--ok-label "go" --cancel-label "close")
 		# result:
 		# $? return 0: click ok, also echo item tag(1/2/3/4)
 		# $? return 1: click cancel
 		[[ $? -eq 1 ]] && MENU_SELECT_ITEM=4
-
+	elif [[ $EXEINFO_GEN_METHOD == "zenity" ]];
+	then
+		MENU_SELECT_ITEM=$(zenity --width=1000 --height=600 --list --title="exe info setting" \
+			--ok-label="go" --cancel-label="close" \
+			--text="select one of items to go" \
+			--column="item" --column="action" \
+			"1" "set exe file location($TEMP_EXENAME)" \
+			"2" "set savedata directory location($TEMP_SAVEDATA_DIR)" \
+			"3" "***write into exeinfo_profile" \
+			"4" "***cancel and exit without saving into exeinfo_profile")
+		# result:
+		# $? return 0: click ok, also echo item tag(1/2/3/4)
+		# $? return 1: click cancel
+		[[ $? -eq 1 ]] && MENU_SELECT_ITEM=4
 	elif [[ $EXEINFO_GEN_METHOD == "read" ]];
 	then
 		while true; do
@@ -117,10 +167,14 @@ EOF
 	fi
 }
 
-function handle_exe_location(){
+function exeinfo_exe_location(){
 	if [[ $EXEINFO_GEN_METHOD == "kdialog" ]];
 	then
 		TEMP_EXEPATH="$(kdialog --geometry 1000x600 --title "select the .exe file" --getopenfilename "$APPIMAGE_CACHE_DIR")"
+		RETURN_STATUS="$?"
+	elif [[ $EXEINFO_GEN_METHOD == "zenity" ]];
+	then
+		TEMP_EXEPATH="$(zenity --width=1000 --height=600 --file-selection --title="select the .exe file" --filename="$APPIMAGE_CACHE_DIR")"
 		RETURN_STATUS="$?"
 	else
 		clear
@@ -136,6 +190,7 @@ function handle_exe_location(){
 		echo "##################################################"
 		echo ""
 		read -e -p "input .exe file path: " -i "$APPIMAGE_CACHE_DIR" TEMP_EXEPATH
+		RETURN_STATUS="$?"
 		TEMP_EXEPATH="$(readlink -f "$TEMP_EXEPATH")"
 		if [[ ! -f "$TEMP_EXEPATH" ]];
 		then
@@ -147,7 +202,6 @@ function handle_exe_location(){
 			TEMP_EXEPATH=""
 			return
 		fi
-		RETURN_STATUS="$?"
 	fi
 
 	if [[ $RETURN_STATUS -eq 0 ]];	# clicked "ok"
@@ -160,6 +214,8 @@ function handle_exe_location(){
 		then
 			TEMP_EXE_LROOT=$APPDIR/usr/share	# .exe file in AppDir, running AppRun directly from AppDir at this moment.
 		else
+			[[ $EXEINFO_GEN_METHOD == "kdialog" ]] && kdialog --error "you selected *.exe file outside of appimage dir."
+			[[ $EXEINFO_GEN_METHOD == "zenity" ]] && zenity --error --text="you selected *.exe file outside of appimage dir."
 			clear
 			echo "########################################"
 			echo "ERROR: .exe file outside of appimage dir." >&2	# outside of AppDir and *.cache. Should not install .exe outside of AppDir or *.cache.
@@ -204,10 +260,14 @@ function handle_exe_location(){
 }
 
 
-function handle_savedata_location(){
+function exeinfo_savedata_location(){
 	if [[ $EXEINFO_GEN_METHOD == "kdialog" ]];
 	then
 		TEMP_SAVEDATAPATH=$(kdialog --geometry 1000x600 --title "select the directory where to save the savedata files" --getexistingdirectory "$APPIMAGE_CACHE_DIR")
+		RETURN_STATUS="$?"
+	elif [[ $EXEINFO_GEN_METHOD == "zenity" ]];
+	then
+		TEMP_SAVEDATAPATH="$(zenity --width=1000 --height=600 --file-selection --directory --title="select the directory where to save the savedata files" --filename="$APPIMAGE_CACHE_DIR")"
 		RETURN_STATUS="$?"
 	else
 		clear
@@ -225,6 +285,7 @@ function handle_savedata_location(){
 		echo "##################################################"
 		echo ""
 		read -e -p "input savedata directory path: " -i "$APPIMAGE_CACHE_DIR" TEMP_SAVEDATAPATH
+		RETURN_STATUS="$?"
 		TEMP_SAVEDATAPATH="$(readlink -f "$TEMP_SAVEDATAPATH")"
 		if [[ ! -d "$TEMP_SAVEDATAPATH" ]];
 		then
@@ -236,7 +297,6 @@ function handle_savedata_location(){
 			TEMP_SAVEDATAPATH=""
 			return
 		fi
-		RETURN_STATUS="$?"
 	fi
 
 	clear
@@ -259,6 +319,8 @@ function handle_savedata_location(){
 			TEMP_SAVEDATA_IN_HOME=1
 			TEMP_SAVEDATA_DIR=$(apprun_realpath "${APPDIR}/home/public_user" "$TEMP_SAVEDATAPATH")
 		else
+			[[ $EXEINFO_GEN_METHOD == "kdialog" ]] && kdialog --error "you selected savedata directory outside of appimage dir."
+			[[ $EXEINFO_GEN_METHOD == "zenity" ]] && zenity --error --text="you selected savedata directory outside of appimage dir."
 			echo "########################################"
 			echo "ERROR: savedata directory outside of appimage dir."	# outside of AppDir and *.appimage.
 			echo "########################################"
@@ -270,7 +332,7 @@ function handle_savedata_location(){
 	unset TEMP_SAVEDATAPATH
 }
 
-function write_exeinfo(){
+function exeinfo_write_file(){
 	if [[ $EXEINFO_GEN_METHOD == "kdialog" ]];
 	then
 		kdialog --geometry 1000x600 --warningcontinuecancel \
@@ -292,6 +354,28 @@ SAVEDATA_DIR=\"$TEMP_SAVEDATA_DIR\"
 
 write into exeinfo_profile?
 "
+		RETURN_NUMBER=$?
+	elif [[ $EXEINFO_GEN_METHOD == "zenity" ]];
+	then
+		zenity --question --ok-label="continue" --text=\
+" \
+old:\n \
+EXE_LDIR=\"$EXE_LDIR\"\n \
+EXE_WROOT=\"$EXE_WROOT\"\n \
+EXE_WDIR=\"$EXE_WDIR\"\n \
+EXENAME=\"$EXENAME\"\n \
+SAVEDATA_IN_HOME=\"$SAVEDATA_IN_HOME\"\n \
+SAVEDATA_DIR=\"$SAVEDATA_DIR\"\n \
+\n \
+new:\n \
+EXE_LDIR=\"$TEMP_EXE_LDIR\"\n \
+EXE_WROOT=\"$TEMP_EXE_WROOT\"\n \
+EXE_WDIR=\"$TEMP_EXE_WDIR\"\n \
+EXENAME=\"$TEMP_EXENAME\"\n \
+SAVEDATA_IN_HOME=\"$TEMP_SAVEDATA_IN_HOME\"\n \
+SAVEDATA_DIR=\"$TEMP_SAVEDATA_DIR\"\n \
+\n \
+write into exeinfo_profile?\n"
 		RETURN_NUMBER=$?
 	elif [[ $EXEINFO_GEN_METHOD == "read" ]];
 	then
@@ -358,6 +442,10 @@ function exeinfo_confirm_exit(){
 	then
 		kdialog --yesno "exit exeinfo setting?"
 		RETURN_NUMBER=$?
+	elif [[ "$EXEINFO_GEN_METHOD" == "zenity" ]];
+	then
+		zenity --question --text="exit exeinfo setting?"
+		RETURN_NUMBER=$?
 	elif [[ "$EXEINFO_GEN_METHOD" == "read" ]];
 	then
 		while true; do
@@ -392,31 +480,35 @@ function exeinfo_confirm_exit(){
 	fi
 }
 
-function exeinfo_gen(){
+function exeinfo_main(){
 	clear
-	temp_exeinfo
-	test_gui
+	exeinfo_load_env
+	exeinfo_test_gui
 	EXIT_MAIN_MENU=0
 	while [[ $EXIT_MAIN_MENU -eq 0 ]];do
 		exeinfo_main_menu
 		clear
 		if [[ $MENU_SELECT_ITEM -eq 1 ]];
 		then 
-			handle_exe_location
+			exeinfo_exe_location
 		elif [[ $MENU_SELECT_ITEM -eq 2 ]];
 		then
-			handle_savedata_location
+			exeinfo_savedata_location
 		elif [[ $MENU_SELECT_ITEM -eq 3 ]];
 		then
-			write_exeinfo
+			exeinfo_write_file
 		elif [[ $MENU_SELECT_ITEM -eq 4 ]];
 		then
 			exeinfo_confirm_exit
+		else
+			echo "[AppRun:plugin_exeinfo] unknown \$MENU_SELECT_ITEM=$MENU_SELECT_ITEM"
+			EXIT_MAIN_MENU=1
 		fi
 	done
 }
 
-[[ "$0" == "${BASH_SOURCE[0]}" ]] && exeinfo_gen
+[[ "$0" == "${BASH_SOURCE[0]}" && $MYAPPDEBUG -eq 1 ]] && exeinfo_test_env
+[[ "$0" == "${BASH_SOURCE[0]}" ]] && exeinfo_main
 
 ##############################################
 
