1.fix savedate loading bug; 2.fix grouped short option bug; 3.use XDG env in exeinfo_profile; 4.add support for proton

diff --git a/usr/bin/myapp b/usr/bin/myapp
--- a/usr/bin/myapp
+++ b/usr/bin/myapp
@@ -2,7 +2,7 @@
 
 # AppRun Script version
 # date -u +%s
-MYAPPRUN_VERSION=1645999388
+MYAPPRUN_VERSION=1646251850
 
 #############################################
 ## prevent running by root/sudo for security concern
@@ -64,11 +64,11 @@ fi
 ##############################################
 ## setup unionfs temp directory for this app
 
-RO_ALLWINESTORGE="$APPDIR/usr/share/myapp" # Use the location where contain $WINEPREFIX, both win32 and win64 WINEPREFIX directory are here.
+RO_MYAPPSTORGE="$APPDIR/usr/share/myapp" # Use the location where contain $WINEPREFIX, both win32 and win64 WINEPREFIX directory are here.
 
-MNT_ALLWINESTORGE="/tmp/$(basename "$APPDIR").unionfs/usr/share/myapp"
+MNT_MYAPPSTORGE="/tmp/$(basename "$APPDIR").unionfs/usr/share/myapp"
 
-TMP_ALLWINESTORGE_OVERLAY="$APPIMAGE_CACHE_DIR/usr/share/myapp"
+TMP_MYAPPSTORGE_OVERLAY="$APPIMAGE_CACHE_DIR/usr/share/myapp"
 
 
 RO_HOMESTORGE="/home/$USER/"
@@ -76,6 +76,11 @@ RO_HOMESTORGE="/home/$USER/"
 MNT_HOMESTORGE="/tmp/$(basename "$APPDIR").unionfs/home/public_user"
 
 TMP_HOMESTORGE_OVERLAY="$APPIMAGE_CACHE_DIR/home/public_user"
+
+
+HOME_REAL="$HOME"
+HOME_FAKE="$MNT_HOMESTORGE"
+
 ##############################################
 
 
@@ -214,6 +219,7 @@ EOF
 #parameters=$(getopt -o swth --long save-data,walkthrough,browser:,test-winetricks,help -n "$0" -- "$@")	# NOTUSED: because $(getopt) cannot ignore unknown options
 
 parameters=$(echo "$@"|tr "=" " ")
+next_parameters=""
 eval set -- "$parameters"
 
 function option_check(){
@@ -283,24 +289,31 @@ while [[ -n "$1" ]] ; do
 			shift ;;
 		--)
 			shift
-			if [[ -z "$*" && -z "$next_parameters" ]];
+			if [[ -z "$@" && -z "$next_parameters" ]];
 			then
 				break
 			elif [[ ! $MYAPPDEBUG -eq 1 ]];
 			then
 				echo "[AppRun] error: not MYAPPDEBUG mode now. prevent to pass any unknown option." >&2
-				echo "[AppRun] error: unknown options: $next_parameters $*" >&2
+				echo "[AppRun] error: unknown options: $next_parameters $@" >&2
 				exit
 			else
 				# then $next_parameters will be passed to wine
-				next_parameters="$next_parameters $*"
+				[[ -z $next_parameters ]] && next_parameters="$@" || next_parameters="$next_parameters $@"
+				shift $#
 				break
 			fi
 			;;
-		*) 
-			if [[ $MYAPPDEBUG -eq 1 ]];
+		*)
+			if [[ "$(option_check $1)" == "short" && ${#1} -gt 2 ]];
 			then
-				next_parameters="$next_parameters $1"
+				parameters="$(getopt -o 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ -n "$0" -- "$1")"
+				shift
+				parameters="$parameters $@"
+				eval set -- "$parameters"
+			elif [[ $MYAPPDEBUG -eq 1 ]];
+			then
+				[[ -z $next_parameters ]] && next_parameters="$1" || next_parameters="$next_parameters $1"
 				shift
 			else
 				echo "[AppRun] error: not MYAPPDEBUG mode now. prevent to pass any unknow option." >&2
@@ -320,14 +333,14 @@ done
 
 # TODO: cannot handle grouped short option, such as "-sw" will be recognized as unknown option instead of "-s -w"
 
-# the rest of option/argument will be passed to wine
+# unused option/argument will be passed to wine
 eval set -- "$next_parameters"
 
 ##############################################
 
 
 ##############################################
-if [[ $LOAD_PROTON=1 ]];
+if [[ $LOAD_PROTON -eq 1 ]];
 then
 	source "$APPDIR"/usr/bin/myapp-plugin-proton
 else
@@ -349,7 +362,7 @@ exeinfo_load_file
 
 if [[ $EXEINFO_GEN_FLAG -eq 1 && $EXEINFO_GEN_METHOD == "cli" ]];
 then
-	exeinfo_main
+	HOME="$HOME_REAL" exeinfo_main
 	exit
 fi
 
@@ -385,9 +398,9 @@ then
 	exit 1
 fi
 
-mkdir -p "$MNT_ALLWINESTORGE" "$TMP_ALLWINESTORGE_OVERLAY"
-#$APPDIR/usr/bin/unionfs -o use_ino,nonempty,uid=$UID -ocow "$TMP_ALLWINESTORGE_OVERLAY"=RW:"$RO_ALLWINESTORGE"=RO "$MNT_ALLWINESTORGE" || exit 1
-"$APPDIR"/usr/bin/unionfs -o use_ino,auto_unmount,nonempty,uid=$UID -ocow "$TMP_ALLWINESTORGE_OVERLAY"=RW:"$RO_ALLWINESTORGE"=RO "$MNT_ALLWINESTORGE" || exit 1
+mkdir -p "$MNT_MYAPPSTORGE" "$TMP_MYAPPSTORGE_OVERLAY"
+#$APPDIR/usr/bin/unionfs -o use_ino,nonempty,uid=$UID -ocow "$TMP_MYAPPSTORGE_OVERLAY"=RW:"$RO_MYAPPSTORGE"=RO "$MNT_MYAPPSTORGE" || exit 1
+"$APPDIR"/usr/bin/unionfs -o use_ino,auto_unmount,nonempty,uid=$UID -ocow "$TMP_MYAPPSTORGE_OVERLAY"=RW:"$RO_MYAPPSTORGE"=RO "$MNT_MYAPPSTORGE" || exit 1
 
 mkdir -p "$MNT_HOMESTORGE" "$TMP_HOMESTORGE_OVERLAY"
 "$APPDIR"/usr/bin/unionfs -o use_ino,auto_unmount,nonempty,uid=$UID -ocow "$TMP_HOMESTORGE_OVERLAY"=RW:"$RO_HOMESTORGE"=RO "$MNT_HOMESTORGE" || exit 1
@@ -405,9 +418,9 @@ function walkthrough_browser(){
 @
 EOF
 
-	for i in $(ls "$MNT_ALLWINESTORGE/myapp_walkthrough"/*.html);
+	for i in $(ls "$MNT_MYAPPSTORGE/myapp_walkthrough"/*.html);
 	do
-		#echo "  file://$MNT_ALLWINESTORGE/drive_d/myapp_walkthrough/$i"
+		#echo "  file://$MNT_MYAPPSTORGE/drive_d/myapp_walkthrough/$i"
 		# ls will output the full path if run -> ls /full/path/to/file/*.html
 		echo "  file://$i"
 	done
@@ -419,7 +432,7 @@ EOF
 
 EOF
 	#TODO: failed to using xdg-open to open html file.
-	i3-sensible-browser "$MNT_ALLWINESTORGE/myapp_walkthrough"/*.html
+	i3-sensible-browser "$MNT_MYAPPSTORGE/myapp_walkthrough"/*.html
 }
 
 ##############################################
@@ -428,24 +441,28 @@ EOF
 ##############################################
 ## game savedata
 function savedata_replace(){
+	HOME="$HOME_FAKE"
+	exeinfo_user_dirs
+	exeinfo_load_file
 	if [[ $SAVEDATA_IN_HOME -eq 0 ]];
 	then
-		mkdir -p "$MNT_ALLWINESTORGE/$SAVEDATA_DIR"
-		cp -r --suffix=.myapp."$USER".backup "$MNT_ALLWINESTORGE/myapp_savedata"/* "$MNT_ALLWINESTORGE/$SAVEDATA_DIR"
+		mkdir -p "$SAVEDATA_DIR"
+		cp -r --suffix=.myapp."$USER".backup "$MNT_MYAPPSTORGE/myapp_savedata"/* "$SAVEDATA_DIR"
 	elif [[ $SAVEDATA_IN_HOME -eq 1 ]];
 	then
-		mkdir -p "$MNT_HOMESTORGE/$SAVEDATA_DIR"
-		cp -r --suffix=.myapp."$USER".backup "$MNT_ALLWINESTORGE/myapp_savedata"/* "$MNT_HOMESTORGE/$SAVEDATA_DIR"
+		mkdir -p "$SAVEDATA_DIR"
+		cp -r --suffix=.myapp."$USER".backup "$MNT_MYAPPSTORGE/myapp_savedata"/* "$SAVEDATA_DIR"
 	fi
 }
 
 function savedata_restore(){
+	HOME="$HOME_FAKE"
 	if [[ $SAVEDATA_IN_HOME -eq 0 ]];
 	then
-		FIND_DIR="$MNT_ALLWINESTORGE/$SAVEDATA_DIR"
+		FIND_DIR="$SAVEDATA_DIR"
 	elif [[ $SAVEDATA_IN_HOME -eq 1 ]];
 	then
-		FIND_DIR="$MNT_HOMESTORGE/$SAVEDATA_DIR"
+		FIND_DIR="$SAVEDATA_DIR"
 	else
 		echo "[AppRun:savedata_restore] error: invalid FIND_DIR, cannot recover user savedata"
 	fi
@@ -466,7 +483,7 @@ cat << EOF
 @
 @
 @
-  your savedata will be saved at file://$TMP_ALLWINESTORGE_OVERLAY/
+  your savedata will be saved at file://$TMP_MYAPPSTORGE_OVERLAY/
 @
 @
 @
@@ -500,7 +517,7 @@ EOF
 
 if [[ $EXEINFO_GEN_FLAG -eq 1 ]];
 then
-	[[ $EXEINFO_GEN_METHOD == "gui" || $EXEINFO_GEN_METHOD == "zenity" || $EXEINFO_GEN_METHOD == "kdialog" ]] && exeinfo_main
+	[[ $EXEINFO_GEN_METHOD == "gui" || $EXEINFO_GEN_METHOD == "zenity" || $EXEINFO_GEN_METHOD == "kdialog" ]] && HOME="$HOME_REAL" exeinfo_main
 fi
 
 
@@ -509,9 +526,9 @@ then
 	[[ -n $MYAPPLANG ]] && LANG=$MYAPPLANG || echo "MYAPPLANG not set, using current LANG:$LANG"
 	# moved home and xdg_config_home env setting to here.
 	# if change $HOME and $XDG_CONFIG_HOME too early, the exeinfo plugin may encounter some error related to file path.
-	export HOME="$MNT_HOMESTORGE"
+	export HOME="$HOME_FAKE"
 	echo \$HOME=$HOME
-	export XDG_CONFIG_HOME="$MNT_HOMESTORGE/.config"
+	export XDG_CONFIG_HOME="$HOME_FAKE/.config"
 	echo \$XDG_CONFIG_HOME=$XDG_CONFIG_HOME
 	echo "*****using $WINEARCH"
 	if [[ $TEST_WINETRICKS_FLAG -eq 1 ]];
@@ -554,7 +571,7 @@ function monitor_exe_running(){
 	# if return out of this function directly without waiting wine shutdown,
 	# unionfs drive will be unmount immediately.
 	# therefore we can add a "wineboot" command to wait for wine saving the registry.
-	[[ ! $EXEINFO_GEN_FLAG -eq 1 ]] && wineboot -s
+	[[ ! $EXEINFO_GEN_FLAG -eq 1 && ! $LOAD_PROTON -eq 1 ]] && wineboot -s
 }
 monitor_exe_running
 
diff --git a/usr/bin/myapp-plugin-exeinfo-gen b/usr/bin/myapp-plugin-exeinfo-gen
--- a/usr/bin/myapp-plugin-exeinfo-gen
+++ b/usr/bin/myapp-plugin-exeinfo-gen
@@ -75,32 +75,130 @@ function apprun_realpath(){
 
 }
 
+function exeinfo_user_dirs(){
+#refer env
+#XDG_DESKTOP_DIR
+#XDG_DOWNLOAD_DIR
+#XDG_TEMPLATES_DIR
+#XDG_PUBLICSHARE_DIR
+#XDG_DOCUMENTS_DIR
+#XDG_MUSIC_DIR
+#XDG_PICTURES_DIR
+#XDG_VIDEOS_DIR
+	XDG_DESKTOP_DIR="$HOME/Desktop"
+	XDG_DOWNLOAD_DIR="$HOME/Downloads"
+	XDG_TEMPLATES_DIR="$HOME/Templates"
+	XDG_PUBLICSHARE_DIR="$HOME/Public"
+	XDG_DOCUMENTS_DIR="$HOME/Documents"
+	XDG_MUSIC_DIR="$HOME/Music"
+	XDG_PICTURES_DIR="$HOME/Pictures"
+	XDG_VIDEOS_DIR="$HOME/Videos"
+	# if user-dirs.dirs exists, it would replace the default setting
+	if [[ -f "$XDG_CONFIG_HOME/user-dirs.dirs" ]];
+	then
+		source "$XDG_CONFIG_HOME/user-dirs.dirs"
+	elif [[ -f "$HOME/.config/user-dirs.dirs" ]];
+	then
+		source "$HOME/.config/user-dirs.dirs"
+	else
+		echo "cannot find user-dirs.dirs setting, using default setting"
+	fi
+
+	FAKE_DESKTOP_DIR_NAME="$(basename "$XDG_DESKTOP_DIR")"
+	FAKE_DOWNLOAD_DIR_NAME="$(basename "$XDG_DOWNLOAD_DIR")"
+	FAKE_TEMPLATES_DIR_NAME="$(basename "$XDG_TEMPLATES_DIR")"
+	FAKE_PUBLICSHARE_DIR_NAME="$(basename "$XDG_PUBLICSHARE_DIR")"
+	FAKE_DOCUMENTS_DIR_NAME="$(basename "$XDG_DOCUMENTS_DIR")"
+	if [[ "${XDG_MUSIC_DIR#"$XDG_DOCUMENTS_DIR"}" != "$XDG_MUSIC_DIR" ]];
+	then
+		FAKE_MUSIC_DIR_NAME="$(basename "$XDG_DOCUMENTS_DIR")/$(basename "$XDG_MUSIC_DIR")"
+	else
+		FAKE_MUSIC_DIR_NAME="$(basename "$XDG_MUSIC_DIR")"
+	fi
+
+	if [[ "${XDG_PICTURES_DIR#"$XDG_DOCUMENTS_DIR"}" != "$XDG_PICTURES_DIR" ]];
+	then
+		FAKE_PICTURES_DIR_NAME="$(basename "$XDG_DOCUMENTS_DIR")/$(basename "$XDG_PICTURES_DIR")"
+	else
+		FAKE_PICTURES_DIR_NAME="$(basename "$XDG_PICTURES_DIR")"
+	fi
+
+	if [[ "${XDG_VIDEOS_DIR#"$XDG_DOCUMENTS_DIR"}" != "$XDG_VIDEOS_DIR" ]];
+	then
+		FAKE_VIDEOS_DIR_NAME="$(basename "$XDG_DOCUMENTS_DIR")/$(basename "$XDG_VIDEOS_DIR")"
+	else
+		FAKE_VIDEOS_DIR_NAME="$(basename "$XDG_VIDEOS_DIR")"
+	fi
+
+	#PROTON_DESKTOP_DIR_NAME="Desktop"
+	#PROTON_DOWNLOAD_DIR_NAME="Downloads"
+	#PROTON_TEMPLATES_DIR_NAME="Templates"
+	#PROTON_PUBLICSHARE_DIR_NAME="Public"
+	#PROTON_DOCUMENTS_DIR_NAME="Documents"
+	#PROTON_MUSIC_DIR_NAME="Music"
+	#PROTON_PICTURES_DIR_NAME="Pictures"
+	#PROTON_VIDEOS_DIR_NAME="Videos"
+}
+
+function exeinfo_convert_xdg_path(){
+	[[ -z "$1" ]] && echo "[exeinfo_check_include_home] ERROR: no argument was input" >&2 && return
+	if [[ ${1#"$XDG_VIDEOS_DIR"} != "$1" ]];
+	then
+		echo '$XDG_VIDEOS_DIR'"${1#"$XDG_VIDEOS_DIR"}"
+	elif [[ ${1#"$XDG_PICTURES_DIR"} != "$1" ]];
+	then
+		echo '$XDG_PICTURES_DIR'"${1#"$XDG_PICTURES_DIR"}"
+	elif [[ ${1#"$XDG_MUSIC_DIR"} != "$1" ]];
+	then
+		echo '$XDG_MUSIC_DIR'"${1#"$XDG_MUSIC_DIR"}"
+	elif [[ ${1#"$XDG_DOCUMENTS_DIR"} != "$1" ]];
+	then
+		echo '$XDG_DOCUMENTS_DIR'"${1#"$XDG_DOCUMENTS_DIR"}"
+	elif [[ ${1#"$XDG_PUBLICSHARE_DIR"} != "$1" ]];
+	then
+		echo '$XDG_PUBLICSHARE_DIR'"${1#"$XDG_PUBLICSHARE_DIR"}"
+	elif [[ ${1#"$XDG_TEMPLATES_DIR"} != "$1" ]];
+	then
+		echo '$XDG_TEMPLATES_DIR'"${1#"$XDG_TEMPLATES_DIR"}"
+	elif [[ ${1#"$XDG_DOWNLOAD_DIR"} != "$1" ]];
+	then
+		echo '$XDG_DOWNLOAD_DIR'"${1#"$XDG_DOWNLOAD_DIR"}"
+	elif [[ ${1#"$XDG_DESKTOP_DIR"} != "$1" ]];
+	then
+		echo '$XDG_DESKTOP_DIR'"${1#"$XDG_DESKTOP_DIR"}"
+	elif [[ ${1#"$HOME"} != "$1" ]];
+	then
+		echo '$HOME'"${1#"$HOME"}"
+	fi
+
+}
+
 function exeinfo_load_file(){
+	unset EXEINFO_CURRENT_PROFILE
 	if [[ -f "${APPIMAGE_CACHE_DIR}/usr/share/myapp/myapp_exeinfo/exeinfo_profile.$LANG" ]];
 	then
-		PENDING_SOURCE_FILE="${APPIMAGE_CACHE_DIR}/usr/share/myapp/myapp_exeinfo/exeinfo_profile.$LANG"
+		EXEINFO_CURRENT_PROFILE="${APPIMAGE_CACHE_DIR}/usr/share/myapp/myapp_exeinfo/exeinfo_profile.$LANG"
 	elif [[ -f "${APPDIR}/usr/share/myapp/myapp_exeinfo/exeinfo_profile.$LANG" ]];
 	then
-		PENDING_SOURCE_FILE="${APPDIR}/usr/share/myapp/myapp_exeinfo/exeinfo_profile.$LANG"
+		EXEINFO_CURRENT_PROFILE="${APPDIR}/usr/share/myapp/myapp_exeinfo/exeinfo_profile.$LANG"
 	elif [[ -f "${APPIMAGE_CACHE_DIR}/usr/share/myapp/myapp_exeinfo/exeinfo_profile" ]];
 	then
-		PENDING_SOURCE_FILE="${APPIMAGE_CACHE_DIR}/usr/share/myapp/myapp_exeinfo/exeinfo_profile"
+		EXEINFO_CURRENT_PROFILE="${APPIMAGE_CACHE_DIR}/usr/share/myapp/myapp_exeinfo/exeinfo_profile"
 	elif [[ -f "${APPDIR}/usr/share/myapp/myapp_exeinfo/exeinfo_profile" ]];
 	then
-		PENDING_SOURCE_FILE="${APPDIR}/usr/share/myapp/myapp_exeinfo/exeinfo_profile"
+		EXEINFO_CURRENT_PROFILE="${APPDIR}/usr/share/myapp/myapp_exeinfo/exeinfo_profile"
 	else
 		echo "cannot find exeinfo_profile for your LANG:$LANG"
 		echo "also cannot find default exeinfo_profile"
 		return
 	fi
 
-	if (cat "$PENDING_SOURCE_FILE" |grep '^[[:blank:]]*[^[:blank:]#]' |grep --quiet -e '$WINEARCH' -e '${WINEARCH}' -e '${WINEARCH:.*}' -e '${WINEARCH%.*}' -e '${WINEARCH#.*}');
+	if (cat "$EXEINFO_CURRENT_PROFILE" |grep '^[[:blank:]]*[^[:blank:]#]' |grep --quiet -e '$WINEARCH' -e '${WINEARCH}' -e '${WINEARCH:.*}' -e '${WINEARCH%.*}' -e '${WINEARCH#.*}');
 	then
-		[[ -z $WINEARCH ]] && echo "[exeinfo_load_file] ERROR: $PENDING_SOURCE_FILE includes \$WINEARCH but \$WINEARCH was not set. Failed to load exeinfo." >&2 && return
+		[[ -z $WINEARCH ]] && echo "[exeinfo_load_file] ERROR: $EXEINFO_CURRENT_PROFILE includes \$WINEARCH but \$WINEARCH was not set. Failed to load exeinfo." >&2 && return
 	fi
 
-	source "$PENDING_SOURCE_FILE"
-	unset PENDING_SOURCE_FILE
+	source "$EXEINFO_CURRENT_PROFILE"
 }
 
 function exeinfo_load_temp(){
@@ -290,13 +388,13 @@ function exeinfo_exe_location(){
 			case "$(basename "$TEMP")" in
 				drive_d)
 					export TEMP_EXE_WROOT="d"
-					#EXE_WDIR=$(apprun_realpath "$MNT_ALLWINESTORGE/drive_d" "$(dirname $TEMP_EXEPATH)")
+					#EXE_WDIR=$(apprun_realpath "$MNT_MYAPPSTORGE/drive_d" "$(dirname $TEMP_EXEPATH)")
 					TEMP_EXE_WDIR="$TEMP_END"
 					break
 					;;
 				drive_c)
 					export TEMP_EXE_WROOT="c"
-					#EXE_WDIR=$(apprun_realpath "$MNT_ALLWINESTORGE/$WINEARCH/drive_c" "$(dirname $TEMP_EXEPATH)")
+					#EXE_WDIR=$(apprun_realpath "$MNT_MYAPPSTORGE/$WINEARCH/drive_c" "$(dirname $TEMP_EXEPATH)")
 					TEMP_EXE_WDIR="$TEMP_END"
 					break
 					;;
@@ -358,24 +456,59 @@ function exeinfo_savedata_location(){
 	fi
 
 	clear
+
+	#if [[ $RETURN_STATUS -eq 0 ]] && (echo "$TEMP_SAVEDATAPATH" | grep --quiet "steamuser");
+	#then
+	#	TEMP_SAVEDATA_KEEP_SEARCH_FLAG=""
+	#	if (echo "$TEMP_SAVEDATAPATH" | grep --quiet "${APPIMAGE_CACHE_DIR}/usr/share/myapp/myapp_prefix/proton.win64/pfx/drive_c/users/steamuser");
+	#	then
+	#		TEMP_SAVEDATA_IN_HOME=1
+	#		TEMP_SAVEDATA_DIR=$(apprun_realpath "${APPIMAGE_CACHE_DIR}/usr/share/myapp/myapp_prefix/proton.win64/pfx/drive_c/users/steamuser" "$TEMP_SAVEDATAPATH")
+	#	#elif (echo "$TEMP_SAVEDATAPATH" | grep --quiet "${APPIMAGE_CACHE_DIR}/usr/share/myapp/myapp_prefix/proton.win32/pfx/drive_c/users/steamuser");
+	#	#then
+	#	#	TEMP_SAVEDATA_IN_HOME=1
+	#	#	TEMP_SAVEDATA_DIR=$(apprun_realpath "${APPIMAGE_CACHE_DIR}/usr/share/myapp/myapp_prefix/proton.win32/pfx/drive_c/users/steamuser" "$TEMP_SAVEDATAPATH")
+	#	elif (echo "$TEMP_SAVEDATAPATH" | grep --quiet "${APPDIR}/usr/share/myapp/myapp_prefix/proton.win64/pfx/drive_c/users/steamuser");
+	#	then
+	#		TEMP_SAVEDATA_IN_HOME=1
+	#		TEMP_SAVEDATA_DIR=$(apprun_realpath "${APPDIR}/usr/share/myapp/myapp_prefix/proton.win64/pfx/drive_c/users/steamuser" "$TEMP_SAVEDATAPATH")
+	#	#elif (echo "$TEMP_SAVEDATAPATH" | grep --quiet "${APPDIR}/usr/share/myapp/myapp_prefix/proton.win32/pfx/drive_c/users/steamuser");
+	#	#then
+	#	#	TEMP_SAVEDATA_IN_HOME=1
+	#	#	TEMP_SAVEDATA_DIR=$(apprun_realpath "${APPDIR}/usr/share/myapp/myapp_prefix/proton.win32/pfx/drive_c/users/steamuser" "$TEMP_SAVEDATAPATH")
+	#	else
+	#		TEMP_SAVEDATA_KEEP_SEARCH_FLAG=1
+	#	fi
+	#fi
+
+	#if [[ $TEMP_SAVEDATA_KEEP_SEARCH_FLAG -eq 1 && $RETURN_STATUS -eq 0 && -n $TEMP_SAVEDATAPATH ]];
 	if [[ $RETURN_STATUS -eq 0 && -n $TEMP_SAVEDATAPATH ]];
 	then
+		export HOME="$HOME_FAKE"
+		exeinfo_user_dirs
 		if [[ "${TEMP_SAVEDATAPATH#"${APPIMAGE_CACHE_DIR}/usr/share/myapp"}" != "$TEMP_SAVEDATAPATH" ]];
 		then
 			TEMP_SAVEDATA_IN_HOME=0
-			TEMP_SAVEDATA_DIR=$(apprun_realpath "${APPIMAGE_CACHE_DIR}/usr/share/myapp" "$TEMP_SAVEDATAPATH")
+			TEMP_SAVEDATA_DIR='MNT_MYAPPSTORGE/'"$(apprun_realpath "${APPIMAGE_CACHE_DIR}/usr/share/myapp" "$TEMP_SAVEDATAPATH")"
 		elif [[ "${TEMP_SAVEDATAPATH#"${APPDIR}/usr/share/myapp"}" != "$TEMP_SAVEDATAPATH" ]];
 		then
 			TEMP_SAVEDATA_IN_HOME=0
-			TEMP_SAVEDATA_DIR=$(apprun_realpath "${APPDIR}/usr/share/myapp" "$TEMP_SAVEDATAPATH")
+			TEMP_SAVEDATA_DIR='MNT_MYAPPSTORGE/'"$(apprun_realpath "${APPDIR}/usr/share/myapp" "$TEMP_SAVEDATAPATH")"
 		elif [[ "${TEMP_SAVEDATAPATH#"${APPIMAGE_CACHE_DIR}/home/public_user/"}" != "$TEMP_SAVEDATAPATH" ]];
 		then
 			TEMP_SAVEDATA_IN_HOME=1
-			TEMP_SAVEDATA_DIR=$(apprun_realpath "${APPIMAGE_CACHE_DIR}/home/public_user" "$TEMP_SAVEDATAPATH")
+			#TEMP_SAVEDATA_DIR=$(apprun_realpath "${APPIMAGE_CACHE_DIR}/home/public_user" "$TEMP_SAVEDATAPATH")
+			TEMP_SAVEDATAPATH=$(apprun_realpath "${APPIMAGE_CACHE_DIR}/home/public_user" "$TEMP_SAVEDATAPATH")
+			TEMP_SAVEDATAPATH="$HOME/$TEMP_SAVEDATAPATH"
+			TEMP_SAVEDATA_DIR="$(exeinfo_convert_xdg_path "$TEMP_SAVEDATAPATH")"
+		#TODO: still need to fix wrong path output
 		elif [[ "${TEMP_SAVEDATAPATH#"${APPDIR}/home/public_user"}" != "$TEMP_SAVEDATAPATH" ]];
 		then
 			TEMP_SAVEDATA_IN_HOME=1
-			TEMP_SAVEDATA_DIR=$(apprun_realpath "${APPDIR}/home/public_user" "$TEMP_SAVEDATAPATH")
+			#TEMP_SAVEDATA_DIR=$(apprun_realpath "${APPDIR}/home/public_user" "$TEMP_SAVEDATAPATH")
+			TEMP_SAVEDATAPATH=$(apprun_realpath "${APPIMAGE_CACHE_DIR}/home/public_user" "$TEMP_SAVEDATAPATH")
+			TEMP_SAVEDATAPATH="$HOME/$TEMP_SAVEDATAPATH"
+			TEMP_SAVEDATA_DIR="$(exeinfo_convert_xdg_path "$TEMP_SAVEDATAPATH")"
 		else
 			[[ $EXEINFO_GEN_METHOD == "kdialog" ]] && kdialog --error "you selected savedata directory outside of appimage dir."
 			[[ $EXEINFO_GEN_METHOD == "zenity" ]] && zenity --width=300 --height=100 --error --text="you selected savedata directory outside of appimage dir."
@@ -386,6 +519,7 @@ function exeinfo_savedata_location(){
 			echo ""
 			TEMP_SAVEDATAPATH=""
 		fi
+		export HOME="$HOME_REAL"
 	fi
 	unset RETURN_STATUS
 	unset TEMP_SAVEDATAPATH
diff --git a/usr/bin/myapp-plugin-proton b/usr/bin/myapp-plugin-proton
--- a/usr/bin/myapp-plugin-proton
+++ b/usr/bin/myapp-plugin-proton
@@ -53,7 +53,7 @@ function wine_search_proton(){
 	do
 		if [[ -x "$PROTON_DIR"/proton ]];
 		then
-			# must use readlink to convert the path, otherwise if directly pass the path including symlink, some local files(such as default_pfx) maybe delete at below function.
+			# must use readlink to convert to absolute path, otherwise if directly pass the path including symlink, some local files(such as default_pfx) maybe delete at below function. because if the symlink is absolute path instead of relative path, it will still show the original path in unionfs.
 			SEARCH_COMPAT_CLIENT_PATH="$(readlink -f "$HOME/$SEARCH_COMPAT_CLIENT_PATH")"
 			SEARCH_COMPAT_CLIENT_PATH="${SEARCH_COMPAT_CLIENT_PATH#"$HOME/"}"
 
@@ -68,7 +68,7 @@ function wine_search_proton(){
 		return
 	elif [[ -x "$HOME/.steam/steam/steamapps/common/Proton - Experimental/proton" ]];
 	then
-		# must use readlink to convert the path, otherwise if directly pass the path including symlink, some local files(such as default_pfx) maybe delete at below function.
+		# must use readlink to convert to absolute path, otherwise if directly pass the path including symlink, some local files(such as default_pfx) maybe delete at below function. because if the symlink is absolute path instead of relative path, it will still show the original path in unionfs.
 		SEARCH_COMPAT_CLIENT_PATH="$(readlink -f "$HOME/.steam/steam")"
 		SEARCH_COMPAT_CLIENT_PATH="${SEARCH_COMPAT_CLIENT_PATH#"$HOME/"}"
 
@@ -77,7 +77,7 @@ function wine_search_proton(){
 		return
 	elif [[ -x "$HOME/.local/share/Steam/steamapps/common/Proton - Experimental/proton" ]];
 	then
-		# must use readlink to convert the path, otherwise if directly pass the path including symlink, some local files(such as default_pfx) maybe delete at below function.
+		# must use readlink to convert to absolute path, otherwise if directly pass the path including symlink, some local files(such as default_pfx) maybe delete at below function. because if the symlink is absolute path instead of relative path, it will still show the original path in unionfs.
 		SEARCH_COMPAT_CLIENT_PATH="$(readlink -f "$HOME/.local/share/Steam")"
 		SEARCH_COMPAT_CLIENT_PATH="${SEARCH_COMPAT_CLIENT_PATH#"$HOME/"}"
 
@@ -126,7 +126,7 @@ function wine_set_env(){
 ## restore wine prefix, should only run this function after unionfs is mounted, because $WINEPREFIX path include the unionfs drive
 function wine_restore_prefix(){
 	[[ $MYAPPDEBUG -eq 1 ]] && echo "run wine_restore_prefix"
-	[[ -z "$MNT_ALLWINESTORGE" ]] && echo "[wine_restore_prefix]:\$MNT_ALLWINESTORGE not set" >&2 && exit
+	[[ -z "$MNT_MYAPPSTORGE" ]] && echo "[wine_restore_prefix]:\$MNT_MYAPPSTORGE not set" >&2 && exit
 	#if [[ "$WINEARCH" == "win32" ]];
 	#then
 	#	[[ ! -x "$HOME/$PROTON_DIR_FROM_HOME/temprun.win32.proton" ]] && cat "$HOME/$PROTON_DIR_FROM_HOME/proton" | sed 's/wine64/wine/g' > "$HOME/$PROTON_DIR_FROM_HOME/temprun.win32.proton"
@@ -143,15 +143,15 @@ function wine_restore_prefix(){
 
 	export STEAM_COMPAT_CLIENT_INSTALL_PATH="$HOME/$SEARCH_COMPAT_CLIENT_PATH"
 	export PATH="$HOME/$PROTON_DIR_FROM_HOME/dist/bin/:$PATH"
-	export STEAM_COMPAT_DATA_PATH="$MNT_ALLWINESTORGE/myapp_prefix/proton.$WINEARCH"
+	export STEAM_COMPAT_DATA_PATH="$MNT_MYAPPSTORGE/myapp_prefix/proton.$WINEARCH"
 	# not necessary to set WINEPREFIX because proton uses $STEAM_COMPAT_DATA_PATH/pfx to decide the WINEPREFIX directory
 	# however, we still set the WINEPREFIX because below lines need $WINEPREFIX
-	export WINEPREFIX="$MNT_ALLWINESTORGE/myapp_prefix/proton.$WINEARCH/pfx"
+	export WINEPREFIX="$MNT_MYAPPSTORGE/myapp_prefix/proton.$WINEARCH/pfx"
 
 	# "rm -rf" included, must check $WINEPREFIX first
 	#[[ -z "$WINEPREFIX" ]] && echo "[myapp:wine_restore_prefix] ERROR:\$WINEPREFIX not set, could not restore wine prefix." >&2 && return
 
-	mkdir -p "$MNT_ALLWINESTORGE/myapp_prefix/proton.$WINEARCH"
+	mkdir -p "$MNT_MYAPPSTORGE/myapp_prefix/proton.$WINEARCH"
 
 	# only setup wineprefix and do nothing
 	if [[ $MYAPPDEBUG -eq 1 ]];
@@ -167,23 +167,64 @@ function wine_restore_prefix(){
 	#echo "disable" > "$WINEPREFIX/.update-timestamp"
 
 	# in proton, also keep y: drive, which is winetricks cache. otherwise it would keep asking you to install mono
-	# TODO: seems not the problem of y: drive. but why wine keep asking to install mono?
+	# TODO: ok...seems not the problem of y: drive. but why wine keep asking to install mono?
 	find "$WINEPREFIX/dosdevices" -mindepth 1 -maxdepth 1 ! -name "c:" ! -name "d:" ! -name "y:" -exec rm -rf "{}" \;
 	[[ ! -L "$WINEPREFIX/dosdevices/c:" ]] && ln -sfn ../drive_c "$WINEPREFIX/dosdevices/c:"
-	[[ ! -L "$WINEPREFIX/dosdevices/d:" ]] && ln -sfn ../../../drive_d "$WINEPREFIX/dosdevices/d:"
-	[[ ! -L "$MNT_ALLWINESTORGE/drive_d/myapp_patch_reg" ]] && ln -sfn ../../../../myapp_patch_reg "$WINEPREFIX/drive_c/myapp_patch_reg"
-	if [[ ! -L "$WINEPREFIX/drive_c/windows/Fonts" ]];
+	[[ ! -L "$WINEPREFIX/dosdevices/d:" ]] && ln -sfn ../../../../drive_d "$WINEPREFIX/dosdevices/d:"
+	#refer path: .../myapp/myapp_prefix/wine.win64/pfx/drive_c/myapp_patch_reg
+	[[ ! -L "$MNT_MYAPPSTORGE/myapp_patch_reg" ]] && ln -sfn ../../../../../myapp_patch_reg "$WINEPREFIX/drive_c/myapp_patch_reg"
+	#if [[ ! -L "$WINEPREFIX/drive_c/windows/Fonts" ]];
+	#then
+	#	rm -rf "$WINEPREFIX/drive_c/windows/Fonts"
+	#	#refer path: .../myapp/myapp_fonts
+	#	#refer path: .../myapp/myapp_prefix/wine.win64/pfx/drive_c/windows/Fonts
+	#	ln -sfnv ../../../../../../myapp_fonts "$WINEPREFIX/drive_c/windows/Fonts"
+	#fi
+
+	# should already load plugin-exeinfo at this moment
+	# should already mount fake home unionfs at this moment
+	exeinfo_user_dirs
+	[[ -z "$MNT_HOMESTORGE" ]] && echo "[wine_restore_prefix]:\$MNT_HOMESTORGE not set" >&2 && return
+	if [[ ! -L "$WINEPREFIX/drive_c/users/steamuser/Documents" ]];
 	then
-		rm -rf "$WINEPREFIX/drive_c/windows/Fonts"
-		#refer path: .../myapp/myapp_fonts
-		#refer path: .../myapp/myapp_prefix/wine.wine64/pfx/drive_c/windows/Fonts
-		ln -sfnv ../../../../../myapp_fonts "$WINEPREFIX/drive_c/windows/Fonts"
+		rm -rf "$WINEPREFIX/drive_c/users/steamuser/Documents"
+		ln -sfn "$MNT_HOMESTORGE/$FAKE_DOCUMENTS_DIR_NAME" "$WINEPREFIX/drive_c/users/steamuser/Documents"
 	fi
+	if [[ ! -L "$WINEPREFIX/drive_c/users/steamuser/Desktop" ]];
+	then
+		rm -rf "$WINEPREFIX/drive_c/users/steamuser/Desktop"
+		ln -sfn "$MNT_HOMESTORGE/$FAKE_DESKTOP_DIR_NAME" "$WINEPREFIX/drive_c/users/steamuser/Desktop"
+	fi
+	if [[ ! -L "$WINEPREFIX/drive_c/users/steamuser/Downloads" ]];
+	then
+		rm -rf "$WINEPREFIX/drive_c/users/steamuser/Downloads"
+		ln -sfn "$MNT_HOMESTORGE/$FAKE_DOWNLOAD_DIR_NAME" "$WINEPREFIX/drive_c/users/steamuser/Downloads"
+	fi
+	if [[ ! -L "$WINEPREFIX/drive_c/users/steamuser/Music" ]];
+	then
+		rm -rf "$WINEPREFIX/drive_c/users/steamuser/Music"
+		ln -sfn "$MNT_HOMESTORGE/$FAKE_MUSIC_DIR_NAME" "$WINEPREFIX/drive_c/users/steamuser/Music"
+	fi
+	if [[ ! -L "$WINEPREFIX/drive_c/users/steamuser/Pictures" ]];
+	then
+		rm -rf "$WINEPREFIX/drive_c/users/steamuser/Pictures"
+		ln -sfn "$MNT_HOMESTORGE/$FAKE_PICTURES_DIR_NAME" "$WINEPREFIX/drive_c/users/steamuser/Pictures"
+	fi
+	if [[ ! -L "$WINEPREFIX/drive_c/users/steamuser/Videos" ]];
+	then
+		rm -rf "$WINEPREFIX/drive_c/users/steamuser/Videos"
+		ln -sfn "$MNT_HOMESTORGE/$FAKE_VIDEOS_DIR_NAME" "$WINEPREFIX/drive_c/users/steamuser/Videos"
+	fi
+}
+
+function wine_shutdown_prefix(){
+	echo wine_shutdown_prefix
+	"$HOME/$PROTON_DIR_FROM_HOME/proton" run wineboot -s
 }
 
 function wine_patch_reg(){
 	[[ $MYAPPDEBUG -eq 1 ]] && echo "run wine_patch_reg"
-	[[ -z "$MNT_ALLWINESTORGE" ]] && echo "[wine_restore_prefix] ERROR:\$MNT_ALLWINESTORGE not set" >&2 && exit
+	[[ -z "$MNT_MYAPPSTORGE" ]] && echo "[wine_restore_prefix] ERROR:\$MNT_MYAPPSTORGE not set" >&2 && exit
 
 	# I tried to disable autostart winedbg via loading the .reg by regedit but failed. therefore I use winetricks to disable autostart debugger.
 	if [[ $MYAPPDEBUG -eq 1 ]];
@@ -194,16 +235,16 @@ function wine_patch_reg(){
 		winetricks autostart_winedbg=disabled >/dev/null 2>&1
 	fi
 
-	[[ -z "$(ls "$MNT_ALLWINESTORGE"/myapp_patch_reg/*.reg 2>/dev/null )" ]] && return
-	for i in $(ls "$MNT_ALLWINESTORGE"/myapp_patch_reg/*.reg); do
+	[[ -z "$(ls "$MNT_MYAPPSTORGE"/myapp_patch_reg/*.reg 2>/dev/null )" ]] && return
+	for i in $(ls "$MNT_MYAPPSTORGE"/myapp_patch_reg/*.reg); do
 		# ls /full/path/of/*.reg will output full path of file, need to use $(basename "$i") to get the file name.
 		[[ -f $i ]] && i=$(basename "$i") || continue
 		#"$HOME/$PROTON_DIR_FROM_HOME/temprun.$WINEARCH.proton" regedit "d:\\myapp_patch_reg\\$i"
 		"$HOME/$PROTON_DIR_FROM_HOME/proton" regedit "d:\\myapp_patch_reg\\$i"
 	done
 
-	[[ -z "$(ls "$MNT_ALLWINESTORGE"/myapp_patch_reg/$WINEARCH/*.reg 2>/dev/null )" ]] && return
-	for i in $(ls "$MNT_ALLWINESTORGE"/myapp_patch_reg/$WINEARCH/*.reg); do
+	[[ -z "$(ls "$MNT_MYAPPSTORGE"/myapp_patch_reg/$WINEARCH/*.reg 2>/dev/null )" ]] && return
+	for i in $(ls "$MNT_MYAPPSTORGE"/myapp_patch_reg/$WINEARCH/*.reg); do
 		# ls /full/path/of/*.reg will output full path of file, need to use $(basename "$i") to get the file name.
 		[[ -f $i ]] && i=$(basename "$i") || continue
 		#"$HOME/$PROTON_DIR_FROM_HOME/temprun.$WINEARCH.proton" regedit "d:\\myapp_patch_reg\\$WINEARCH\\$i"
@@ -218,9 +259,9 @@ function wine_run_winetricks(){
 	wine_restore_prefix
 	#"$APPDIR"/usr/bin/winetricks sandbox	# this command run too slow
 	wine_patch_reg
-	#wineboot -es	# this command run too slow
 	#"$HOME/$PROTON_DIR_FROM_HOME/temprun.$WINEARCH.proton" run wineboot -s
-	"$HOME/$PROTON_DIR_FROM_HOME/proton" run wineboot -s
+	wine_shutdown_prefix
+
 	if [[ $MYAPPDEBUG -eq 1 ]];
 	then
 		"$APPDIR"/usr/bin/winetricks "$@"
@@ -237,13 +278,11 @@ function wine_run_exe(){
 	[[ $WALKTHROUGH_FLAG -eq 1 ]] && walkthrough_browser
 	[[ $SAVEDATA_FLAG -eq 1 ]] && savedata_replace
 
-	cd "$MNT_ALLWINESTORGE/$EXE_LDIR" || exit 2 # Use the app installed location. Some .exe may not run if not cd into excute directory
+	cd "$MNT_MYAPPSTORGE/$EXE_LDIR" || exit 2 # Use the app installed location. Some .exe may not run if not cd into excute directory
 
 	wine_patch_reg
-
-	#wineboot -es	# this command run too slow
 	#"$HOME/$PROTON_DIR_FROM_HOME/temprun.$WINEARCH.proton" run wineboot -s
-	"$HOME/$PROTON_DIR_FROM_HOME/proton" run wineboot -s
+	wine_shutdown_prefix
 
 	#"$APPDIR"/usr/bin/winetricks sandbox >/dev/null 2>&1 && wine "${EXE_WROOT}:\\${EXE_WDIR}\\$EXENAME" "$@" 	# must use dos-style path instead of unix-style path if winetricks sandbox was set.
 	if [[ $MYAPPDEBUG -eq 1 ]];
