update version number

diff --git a/usr/bin/myapp-plugin-proton b/usr/bin/myapp-plugin-proton
--- a/usr/bin/myapp-plugin-proton
+++ b/usr/bin/myapp-plugin-proton
@@ -34,7 +34,7 @@ function wine_detect_winetricks(){
 	# both are not exist
 	if [[ -z "$LOCAL_WINETRICKS_BIN" && -z "$APPIMAGE_WINETRICKS_BIN" ]];
 	then
-		echo "command not found: winetricks"
+		echo "[$(basename "${BASH_SOURCE[0]}")] ERROR: command not found: winetricks"
 		exit 1
 	fi
 
@@ -162,7 +162,7 @@ function wine_set_env(){
 
 	wine_search_proton
 
-	[[ -z "$MNT_MYAPPSTORGE" ]] && echo "[$(basename "${BASH_SOURCE[0]}"):${FUNCNAME[0]}] ERROR:\$MNT_MYAPPSTORGE not set" >&2 && exit
+	[[ -z "$MNT_MYAPPSTORGE" ]] && echo "[$(basename "${BASH_SOURCE[0]}"):${FUNCNAME[0]}] ERROR: \$MNT_MYAPPSTORGE not set" >&2 && exit
 	# not necessary to set WINEPREFIX because proton uses $STEAM_COMPAT_DATA_PATH/pfx to decide the WINEPREFIX directory
 	# however, we still set the WINEPREFIX because below lines need $WINEPREFIX
 	export WINEPREFIX="$MNT_MYAPPSTORGE/myapp_prefix/proton.$WINEARCH/pfx"
@@ -323,13 +323,15 @@ function wine_wait_shutdown(){
 	# NOTUSED: deirectly use wineserver instead of "proton run wineserver" because proton will exec wineserver in background
 	#"$HOME/$PROTON_DIR_FROM_HOME/proton" run wineserver -w
 	wineserver -w
-	if [[ $? -ne 0 ]];
+	WINE_WINESERVER_EXIT=$?
+	if [[ $WINE_WINESERVER_EXIT -ne 0 ]];
 	then
-		echo "[$(basename "${BASH_SOURCE[0]}"):${FUNCNAME[0]}] ERROR: wineserver did not shutdown normally. exit code=$?" >&2
+		echo "[$(basename "${BASH_SOURCE[0]}"):${FUNCNAME[0]}] ERROR: wineserver did not shutdown normally. exit code=$WINE_WINESERVER_EXIT" >&2
 		wineserver -k
 		#NOTUSED: should not exit here. it may skip atexit() and let unionfs remain in background
 		#exit
 	fi
+	unset WINE_WINESERVER_EXIT
 
 	echo "end >>>>>>>> [${FUNCNAME[0]}]" >&3
 }
