fix wine remain in background

diff --git a/usr/bin/myapp b/usr/bin/myapp
--- a/usr/bin/myapp
+++ b/usr/bin/myapp
@@ -2,14 +2,14 @@
 
 # AppRun Script version
 # date -u +%s
-MYAPPRUN_VERSION=1647961804
+MYAPPRUN_VERSION=1648144296
 
 #############################################
 ## prevent running by root/sudo for security concern
 if [[ $(id -u) -eq 0 ]];
 then
-	echo "[AppRun]: prevent running by root/sudo"
-	echo "[AppRun]: you should not using root/sudo to run this application"
+	echo "[$(basename "${BASH_SOURCE[0]}")] ERROR: prevent running by root/sudo"
+	echo "[$(basename "${BASH_SOURCE[0]}")] ERROR: you should not using root/sudo to run this application"
 	exit
 fi
 #############################################
@@ -17,10 +17,19 @@ fi
 
 #############################################
 function debug_print_env(){
-	for i in "$@";
-	do
-		eval echo "\ \ \ \ $i=\$$i"
-	done
+	if [[ $MYAPPDEBUG_COLOR -eq 1 ]];
+	then
+		for i in "$@";
+		do
+			#eval echo -e "\ \ \ \ '\033[43m'$i'\033[0m'=\$$i"
+			eval echo -e "\ \ \ \ '\033[1;93m'$i'\033[0m'=\$$i"
+		done
+	else
+		for i in "$@";
+		do
+			eval echo "\ \ \ \ $i=\$$i"
+		done
+	fi
 }
 
 function debug_fd_switch(){
@@ -70,10 +79,10 @@ SELF=$(readlink -f "$0")
 if [[ -x "$(command -v unionfs)" ]];
 then
 	UNIONFS_BIN="$(command -v unionfs)"
-	[[ $MYAPPDEBUG -eq 1 ]] && debug_print_env UNIONFS_BIN
+	debug_print_env UNIONFS_BIN >&3 2>&4
 else
 	UNIONFS_BIN="$APPDIR/usr/bin/unionfs"
-	[[ $MYAPPDEBUG -eq 1 ]] && debug_print_env UNIONFS_BIN
+	debug_print_env UNIONFS_BIN >&3 2>&4
 fi
 
 # keep a backup of $PATH location. Because later I will compare the version number of local winetricks and builtin winetricks.
@@ -97,6 +106,7 @@ export QT_PLUGIN_PATH="${APPDIR}/usr/lib/qt4/plugins/:${APPDIR}/usr/lib/i386-lin
 ##############################################
 ## check if it is running from appimage or running from appdir
 
+# if run directly from AppDir. 
 if [[ -z ${APPIMAGE} ]];
 then
 	export APPIMAGE="$APPDIR"
@@ -221,6 +231,9 @@ EOF
 #parameters=$(getopt -o swth --long save-data,walkthrough,browser:,test-winetricks,help -n "$0" -- "$@")	# NOTUSED: because $(getopt) cannot ignore unknown options
 
 parameters=$(echo "$@"|tr "=" " ")
+# in this script, if I initialize a variable to empty,
+# that means I want to avoid some unexpected error,
+# in case user pass an initial value in command line
 next_parameters=""
 eval set -- "$parameters"
 
@@ -254,7 +267,7 @@ while [[ -n "$1" ]] ; do
 			shift ;;
 		--browser)
 			#i3-sensible-browser will choose $BROWSER to open walkthrough first
-			[[ $(option_check "$2") != "none" ]] && echo "invalid option $1" >&2 && exit 1
+			[[ $(option_check "$2") != "none" ]] && echo "[$(basename "${BASH_SOURCE[0]}")] ERROR: invalid option $1" >&2 && exit 1
 			BROWSER="$2"
 			shift 2;;
 		-t| --test-winetricks)
@@ -298,8 +311,8 @@ while [[ -n "$1" ]] ; do
 				break
 			elif [[ ! $MYAPPDEBUG -eq 1 ]];
 			then
-				echo "[AppRun] error: not MYAPPDEBUG mode now. prevent to pass any unknown option." >&2
-				echo "[AppRun] error: unknown options: $next_parameters $@" >&2
+				echo "[$(basename "${BASH_SOURCE[0]}")] ERROR: not MYAPPDEBUG mode now. prevent to pass any unknown option." >&2
+				echo "[$(basename "${BASH_SOURCE[0]}")] ERROR: unknown options: $next_parameters $@" >&2
 				exit
 			else
 				# then $next_parameters will be passed to wine
@@ -321,8 +334,8 @@ while [[ -n "$1" ]] ; do
 				[[ -z $next_parameters ]] && next_parameters="$1" || next_parameters="$next_parameters $1"
 				shift
 			else
-				echo "[AppRun] error: not MYAPPDEBUG mode now. prevent to pass any unknow option." >&2
-				echo "[AppRun] error: unknown options: $1" >&2
+				echo "[$(basename "${BASH_SOURCE[0]}")] ERROR: not MYAPPDEBUG mode now. prevent to pass any unknow option." >&2
+				echo "[$(basename "${BASH_SOURCE[0]}")] ERROR: unknown options: $1" >&2
 				exit
 			fi
 			;;
@@ -349,13 +362,17 @@ if [[ -d ${APPIMAGE}.cache ]];
 then
 	APPIMAGE_CACHE_DIR="${APPIMAGE}.cache"
 else
-	echo "directory  ${APPIMAGE}.cache/ not exist."
-	echo "all data will be saved in /tmp/$(basename "$APPIMAGE").cache/ , which will be deleted after restart computer."
-	echo "to keep your data, please run:"
+	echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
+	echo "@"
+	echo "  directory ${APPIMAGE}.cache/ not exist."
+	echo "  all data will be saved in /tmp/$(basename "$APPIMAGE").cache/ , which will be deleted after restart computer."
+	echo "  to keep your data, please run:"
 	echo ""
-	[[ -n $ARGV0 ]] && echo "  $ARGV0 --portable-cache" || echo "  ${APPIMAGE}/AppRun --portable-cache"
+	[[ -n $ARGV0 ]] && echo "    $ARGV0 --portable-cache" || echo "    ${APPIMAGE}/AppRun --portable-cache"
 	echo ""
-	echo "to create a cache directory."
+	echo "  to create a cache directory."
+	echo "@"
+	echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
 	mkdir -p "/tmp/$(basename "$APPIMAGE").cache"
 	APPIMAGE_CACHE_DIR="/tmp/$(basename "$APPIMAGE").cache"
 fi
@@ -432,7 +449,7 @@ else
 	source "$APPDIR"/usr/bin/myapp-plugin-wine
 fi
 wine_set_env
-debug_print_env "APPDIR" "WINEPREFIX"
+MYAPPDEBUG_COLOR=1 debug_print_env "APPDIR" "WINEPREFIX"
 ##############################################
 
 
@@ -480,7 +497,7 @@ echo "[unionfs:0%] mount unionfs"
 # before setup unionfs temp directory, check if exe is already running
 if [[ -n "$EXENAME" && -n "$(pgrep -fi "$EXENAME")" ]];
 then 
-	echo "seems $EXENAME has been launched and is still running, plsease kill the process if the application encountered error" >&2
+	echo "[$(basename "${BASH_SOURCE[0]}")] ERROR: seems $EXENAME has been launched and is still running, plsease kill the process if the application encountered error" >&2
 	exit 1
 fi
 
@@ -501,7 +518,7 @@ fi
 
 PID_MYAPPSTORGE="$(pgrep -a unionfs | grep "$MNT_MYAPPSTORGE" | awk '{print $1}')"
 PID_HOMESTORGE="$(pgrep -a unionfs | grep "$MNT_HOMESTORGE" | awk '{print $1}')"
-debug_print_env "PID_MYAPPSTORGE" "PID_HOMESTORGE"
+MYAPPDEBUG_COLOR=1 debug_print_env "PID_MYAPPSTORGE" "PID_HOMESTORGE"
 echo "[unionfs:100%] mount unionfs"
 ##############################################
 
@@ -509,9 +526,9 @@ echo "[unionfs:100%] mount unionfs"
 ##############################################
 ## trap exit setting
 function atexit() {
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "start >>>>>>>> [${FUNCNAME[0]}]"
+	echo "start >>>>>>>> [${FUNCNAME[0]}]" >&3
 
-	ATEXIT_FLAG=1
+	export ATEXIT_FLAG=1
 
 	# "rm -rf" included, must check env first.
 	[[ -z "$APPDIR" ]] && echo "[myapp:atexit] ERROR:\$APPDIR not set, could not clean temp files" >&2 && return
@@ -530,6 +547,12 @@ function atexit() {
 		wine_restore_prefix >&3 2>&4
 		echo "[${FUNCNAME[0]}:30%] wait shutdown prefix..."
 		wine_wait_shutdown >&3 2>&4
+		# "wineserver -k" was included in wine_wait_shutdown, but still make second attempt here if previous step was interrupted.
+		# to ensure all the exe process are killed
+		if [[ $? -ne 0 ]];
+		then
+			wineserver -k
+		fi
 
 		[[ $SAVEDATA_FLAG -eq 1 ]] && savedata_restore
 	fi
@@ -548,8 +571,8 @@ function atexit() {
 	rm -rf "$APPIMAGE_CACHE_DIR/usr/share/myapp"/.unionfs* >/dev/null 2>&1
 	rm -rf "$APPIMAGE_CACHE_DIR/home/public_user"/.unionfs* >/dev/null 2>&1
 
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "end <<<<<<<< [${FUNCNAME[0]}]"
 	echo "[${FUNCNAME[0]}:100%] ended"
+	echo "end >>>>>>>> [${FUNCNAME[0]}]" >&3
 }
 
 function preexit(){
@@ -573,7 +596,7 @@ trap preexit SIGHUP SIGINT SIGQUIT SIGKILL SIGTERM
 ##############################################
 ## show the game walkthrough, you can see this info when using commandline to launch this app.
 function walkthrough_browser(){
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "start >>>>>>>> [${FUNCNAME[0]}]"
+	echo "start >>>>>>>> [${FUNCNAME[0]}]" >&3
 
 	cat << EOF
 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@ -611,7 +634,7 @@ EOF
 	[[ -n "$(find "$MNT_MYAPPSTORGE/myapp_walkthrough" -mindepth 1 -maxdepth 1 -name "*.html")" ]] && i3-sensible-browser "$MNT_MYAPPSTORGE/myapp_walkthrough"/*.html
 	[[ -n "$(find "$MNT_MYAPPSTORGE/myapp_walkthrough" -mindepth 1 -maxdepth 1 -name "*.pdf")" ]] && i3-sensible-browser "$MNT_MYAPPSTORGE/myapp_walkthrough"/*.pdf
 
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "end <<<<<<<< [${FUNCNAME[0]}]"
+	echo "end >>>>>>>> [${FUNCNAME[0]}]" >&3
 }
 
 ##############################################
@@ -620,7 +643,7 @@ EOF
 ##############################################
 ## game savedata
 function savedata_replace(){
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "start >>>>>>>> [${FUNCNAME[0]}]"
+	echo "start >>>>>>>> [${FUNCNAME[0]}]" >&3
 
 	HOME="$HOME_FAKE"
 	exeinfo_user_dirs
@@ -635,11 +658,11 @@ function savedata_replace(){
 		cp -r --suffix=.myapp."$USER".backup "$MNT_MYAPPSTORGE/myapp_savedata"/* "$SAVEDATA_DIR"
 	fi
 
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "end <<<<<<<< [${FUNCNAME[0]}]"
+	echo "end >>>>>>>> [${FUNCNAME[0]}]" >&3
 }
 
 function savedata_restore(){
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "start >>>>>>>> [${FUNCNAME[0]}]"
+	echo "start >>>>>>>> [${FUNCNAME[0]}]" >&3
 
 	HOME="$HOME_FAKE"
 	if [[ -z "$SAVEDATA_DIR" ]];
@@ -668,25 +691,28 @@ function savedata_restore(){
 	echo ""
 	unset SAVEDATA_BACKUP
 
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "end <<<<<<<< [${FUNCNAME[0]}]"
+	echo "end >>>>>>>> [${FUNCNAME[0]}]" >&3
 }
 
 function savedata_show_location(){
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "start >>>>>>>> [${FUNCNAME[0]}]"
+	echo "start >>>>>>>> [${FUNCNAME[0]}]" >&3
 
 cat << EOF
 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
 @
 @
 @
-  your savedata will be saved at file://$TMP_MYAPPSTORGE_OVERLAY/
+  your files are saved in:
+@
+    file://$TMP_MYAPPSTORGE_OVERLAY/
+    file://$TMP_HOMESTORGE_OVERLAY/
 @
 @
 @
 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
 EOF
 
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "end <<<<<<<< [${FUNCNAME[0]}]"
+	echo "end >>>>>>>> [${FUNCNAME[0]}]" >&3
 }
 
 ##############################################
@@ -714,6 +740,10 @@ EOF
 ## launch app
 
 function myapp_launch(){
+	# should mount unionfs before run exeinfo generator
+	# because zenity and kdialog may read the config files in $HOME
+	# what is more, it may need to use $XDG_{DOCUMENTS,DOWNLOAD,...}_DIR to 
+	# calculate the relative path.
 	if [[ $EXEINFO_GEN_FLAG -eq 1 ]];
 	then
 		# should use real $HOME to run
@@ -732,7 +762,7 @@ function myapp_launch(){
 		[[ -n $MYAPPLANG ]] && LANG=$MYAPPLANG || echo "MYAPPLANG not set, using current LANG:$LANG"
 		export HOME="$HOME_FAKE"
 		export XDG_CONFIG_HOME="$HOME_FAKE/.config"
-		debug_print_env "HOME" "XDG_CONFIG_HOME" "WINETRICKS_BIN"
+		MYAPPDEBUG_COLOR=1 debug_print_env "HOME" "XDG_CONFIG_HOME" "WINETRICKS_BIN"
 		echo "*****using $WINEARCH"
 		if [[ $TEST_WINETRICKS_FLAG -eq 1 ]];
 		then
@@ -752,7 +782,7 @@ myapp_launch
 # monitor if the .exe is still running
 # however, if the .exe file is only a launcher to launch other .exe files. pls change below code to monitor other the correct *.exe files.
 function monitor_exe_running(){
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "start >>>>>>>> [${FUNCNAME[0]}]"
+	echo "start >>>>>>>> [${FUNCNAME[0]}]" >&3
 
 	# if you find the $EXENAME is only a launcher to launch other *.exe,
 	# you can uncomment below line to change the $EXENAME to another name.
@@ -775,7 +805,7 @@ function monitor_exe_running(){
 		fi
 	done
 
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "end <<<<<<<< [${FUNCNAME[0]}]"
+	echo "end >>>>>>>> [${FUNCNAME[0]}]" >&3
 }
 [[ ! $EXEINFO_GEN_FLAG -eq 1 ]] && monitor_exe_running
 
diff --git a/usr/bin/myapp-plugin-exeinfo b/usr/bin/myapp-plugin-exeinfo
--- a/usr/bin/myapp-plugin-exeinfo
+++ b/usr/bin/myapp-plugin-exeinfo
@@ -35,7 +35,7 @@ function apprun_realpath(){
 	
 	if [[ -z $1 || -z $2 ]];
 	then
-		echo "[apprun_realpath] error: please inpute two variables." >&2
+		echo "[$(basename "${BASH_SOURCE[0]}"):${FUNCNAME[0]}] ERROR: please inpute two variables." >&2
 		exit 1
 	fi
 	
@@ -126,7 +126,7 @@ function exeinfo_user_dirs(){
 function exeinfo_convert_xdg_path(){
 	# when write into exeinfo_profile
 	# write env name itself and prevent escaping
-	[[ -z "$1" ]] && echo "[exeinfo_check_include_home] ERROR: no argument was input" >&2 && return
+	[[ -z "$1" ]] && echo "[$(basename "${BASH_SOURCE[0]}"):${FUNCNAME[0]}] ERROR: no argument was input" >&2 && return
 	if [[ ${1#"$XDG_VIDEOS_DIR"} != "$1" ]];
 	then
 		echo '$XDG_VIDEOS_DIR'"${1#"$XDG_VIDEOS_DIR"}"
@@ -178,9 +178,10 @@ function exeinfo_load_file(){
 		return
 	fi
 
+	# only for test
 	if (cat "$EXEINFO_CURRENT_PROFILE" |grep '^[[:blank:]]*[^[:blank:]#]' |grep --quiet -e '$WINEARCH' -e '${WINEARCH}' -e '${WINEARCH:.*}' -e '${WINEARCH%.*}' -e '${WINEARCH#.*}');
 	then
-		[[ -z $WINEARCH ]] && echo "[exeinfo_load_file] ERROR: $EXEINFO_CURRENT_PROFILE includes \$WINEARCH but \$WINEARCH was not set. Failed to load exeinfo." >&2 && return
+		[[ -z $WINEARCH ]] && echo "[$(basename "${BASH_SOURCE[0]}"):${FUNCNAME[0]}] ERROR: $EXEINFO_CURRENT_PROFILE includes \$WINEARCH but \$WINEARCH was not set. Failed to load exeinfo." >&2 && return
 	fi
 
 	source "$EXEINFO_CURRENT_PROFILE"
@@ -240,7 +241,7 @@ function exeinfo_test_gui(){
 	then
 		return
 	else
-		echo "unknow option $EXEINFO_GEN_METHOD" >&2
+		echo "[$(basename "${BASH_SOURCE[0]}"):${FUNCNAME[0]}] ERROR: unknow option $EXEINFO_GEN_METHOD" >&2
 		EXIT_MAIN_MENU=1
 	fi
 
@@ -353,7 +354,7 @@ function exeinfo_exe_location(){
 		then
 			clear
 			echo "########################################"
-			echo "invalid file name: $TEMP_EXEPATH"
+			echo "ERROR: invalid file name: $TEMP_EXEPATH" >&2
 			echo "########################################"
 			echo ""
 			TEMP_EXEPATH=""
@@ -452,7 +453,7 @@ function exeinfo_savedata_location(){
 		then
 			clear
 			echo "########################################"
-			echo "invalid directory name: $TEMP_SAVEDATAPATH"
+			echo "ERROR: invalid directory name: $TEMP_SAVEDATAPATH" >&2
 			echo "########################################"
 			echo ""
 			TEMP_SAVEDATAPATH=""
@@ -518,7 +519,7 @@ function exeinfo_savedata_location(){
 			[[ $EXEINFO_GEN_METHOD == "zenity" ]] && zenity --width=300 --height=100 --error --text="you selected savedata directory outside of appimage dir."
 			echo "########################################"
 			# outside of AppDir and *.appimage.
-			echo "ERROR: savedata directory outside of appimage dir."
+			echo "ERROR: savedata directory outside of appimage dir." >&2
 			echo "########################################"
 			echo ""
 			TEMP_SAVEDATAPATH=""
@@ -566,6 +567,7 @@ please use locale-gen to generate locale setting first.\n" \
 		echo "  set \$LANG for this game:"
 		echo "  supported locale in current system:"
 		echo ""
+		#TODO: only show *.UTF-8 in result
 		localectl list-locales
 		echo ""
 		echo "  you can only choose one of above items to setup."
@@ -587,7 +589,7 @@ please use locale-gen to generate locale setting first.\n" \
 			TEMP_MYAPPLANG=$TEMP_LANG
 		else	
 			echo "########################################"
-			echo "ERROR: unsupport MYAPPLANG: $TEMP_LANG"
+			echo "ERROR: unsupport MYAPPLANG: $TEMP_LANG" >&2
 			echo "########################################"
 			echo ""
 		fi
@@ -749,7 +751,7 @@ function exeinfo_confirm_exit(){
 		clear
 		return
 	else
-		echo "[AppRun_exeinfo_gen:exeinfo_confirm_exit] unknow error"
+		echo "[$(basename "${BASH_SOURCE[0]}"):${FUNCNAME[0]}] unknow error" >&2
 		EXIT_MAIN_MENU=1
 	fi
 }
@@ -778,7 +780,7 @@ function exeinfo_main(){
 		then
 			exeinfo_confirm_exit
 		else
-			echo "[AppRun:plugin_exeinfo] unknown \$MENU_SELECT_ITEM=$MENU_SELECT_ITEM"
+			echo "[$(basename "${BASH_SOURCE[0]}"):${FUNCNAME[0]}] ERROR: unknown \$MENU_SELECT_ITEM=$MENU_SELECT_ITEM"
 			EXIT_MAIN_MENU=1
 		fi
 	done
@@ -787,9 +789,9 @@ function exeinfo_main(){
 [[ "$0" == "${BASH_SOURCE[0]}" && $MYAPPDEBUG -eq 1 ]] && exeinfo_test_env
 if [[ "$0" == "${BASH_SOURCE[0]}" ]];
 then
-	[[ -n $APPDIR ]] || echo "[AppRun:plugin_exeinfo] required \$APPDIR but it was not set"
-	[[ -n $APPIMAGE_CACHE_DIR ]] || echo "[AppRun:plugin_exeinfo] required \$APPIMAGE_CACHE_DIR but it was not set"
-	[[ -n $EXEINFO_GEN_METHOD ]] || echo "[AppRun:plugin_exeinfo] required \$EXEINFO_GEN_METHOD but it was not set"
+	[[ -n $APPDIR ]] || echo "[$(basename "${BASH_SOURCE[0]}")] required \$APPDIR but it was not set" >&2
+	[[ -n $APPIMAGE_CACHE_DIR ]] || echo "[$(basename "${BASH_SOURCE[0]}")] required \$APPIMAGE_CACHE_DIR but it was not set" >&2
+	[[ -n $EXEINFO_GEN_METHOD ]] || echo "[$(basename "${BASH_SOURCE[0]}")] required \$EXEINFO_GEN_METHOD but it was not set" >&2
 	[[ -n $APPDIR || -n $APPIMAGE_CACHE_DIR || -n $EXEINFO_GEN_METHOD ]] || return
 	exeinfo_main
 fi
diff --git a/usr/bin/myapp-plugin-proton b/usr/bin/myapp-plugin-proton
--- a/usr/bin/myapp-plugin-proton
+++ b/usr/bin/myapp-plugin-proton
@@ -4,7 +4,7 @@
 ## test env
 function wine_test_env(){
 	# these env should be passed to this script
-	echo "[myapp-exeinfo-plugin-gen]: test env"
+	echo "[$(basename "${BASH_SOURCE[0]}")]: test env"
 	echo "required:"
 	debug_print_env APPDIR APPIMAGE_CACHE_DIR EXEINFO_GEN_METHOD
 	echo "optional:"
@@ -61,7 +61,7 @@ function wine_detect_winetricks(){
 
 ##############################################
 function wine_search_proton(){
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "start >>>>>>>> [${FUNCNAME[0]}]"
+	echo "start >>>>>>>> [${FUNCNAME[0]}]" >&3
 	# you need to install steam proton before you use proton mode
 	# defined this function to search local proton
 	# if several version of proton are found
@@ -126,11 +126,11 @@ function wine_search_proton(){
 		return
 	else
 		unset SEARCH_COMPAT_CLIENT_PATH
-		echo "[myapp-plugin-proton] ERROR: Proton not found" >&2
+		echo "[$(basename "${BASH_SOURCE[0]}"):${FUNCNAME[0]}] ERROR: Proton not found" >&2
 		exit
 	fi
 
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "end <<<<<<<< [${FUNCNAME[0]}]"
+	echo "end >>>>>>>> [${FUNCNAME[0]}]" >&3
 }
 ##############################################
 
@@ -138,7 +138,7 @@ function wine_search_proton(){
 ##############################################
 ## setup WINE env
 function wine_set_env(){
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "start >>>>>>>> [${FUNCNAME[0]}]"
+	echo "start >>>>>>>> [${FUNCNAME[0]}]" >&3
 
 	# default to run win64
 	if [[ "$WINEARCH" == "win32" || $(getconf LONG_BIT) -eq 32 ]];
@@ -162,12 +162,12 @@ function wine_set_env(){
 
 	wine_search_proton
 
-	[[ -z "$MNT_MYAPPSTORGE" ]] && echo "[wine_restore_prefix] ERROR:\$MNT_MYAPPSTORGE not set" >&2 && exit
+	[[ -z "$MNT_MYAPPSTORGE" ]] && echo "[$(basename "${BASH_SOURCE[0]}"):${FUNCNAME[0]}] ERROR:\$MNT_MYAPPSTORGE not set" >&2 && exit
 	# not necessary to set WINEPREFIX because proton uses $STEAM_COMPAT_DATA_PATH/pfx to decide the WINEPREFIX directory
 	# however, we still set the WINEPREFIX because below lines need $WINEPREFIX
 	export WINEPREFIX="$MNT_MYAPPSTORGE/myapp_prefix/proton.$WINEARCH/pfx"
 
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "end <<<<<<<< [${FUNCNAME[0]}]"
+	echo "end >>>>>>>> [${FUNCNAME[0]}]" >&3
 }
 ##############################################
 
@@ -175,9 +175,9 @@ function wine_set_env(){
 ##############################################
 ## restore wine prefix, should ensure unionfs is mounted before run this function, because $WINEPREFIX path include the unionfs drive
 function wine_restore_prefix(){
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "start >>>>>>>> [${FUNCNAME[0]}]"
+	echo "start >>>>>>>> [${FUNCNAME[0]}]" >&3
 
-	[[ -z "$MNT_MYAPPSTORGE" ]] && echo "[wine_restore_prefix] ERROR:\$MNT_MYAPPSTORGE not set" >&2 && exit
+	[[ -z "$MNT_MYAPPSTORGE" ]] && echo "[$(basename "${BASH_SOURCE[0]}"):${FUNCNAME[0]}] ERROR:\$MNT_MYAPPSTORGE not set" >&2 && exit
 
 	# keep these comment, may support 32bit proton later
 	#if [[ "$WINEARCH" == "win32" ]];
@@ -238,10 +238,11 @@ function wine_restore_prefix(){
 	# should already load plugin-exeinfo at this moment
 	# should already mount fake home unionfs at this moment
 	exeinfo_user_dirs
-	[[ -z "$MNT_HOMESTORGE" ]] && echo "[wine_restore_prefix]:\$MNT_HOMESTORGE not set" >&2 && return
+	[[ -z "$MNT_HOMESTORGE" ]] && echo "[$(basename "${BASH_SOURCE[0]}"):${FUNCNAME[0]}] ERROR: \$MNT_HOMESTORGE not set" >&2 && return
 
 	# manually redirect xdg dirs to fake home
 	# if proton motify files in $HOME, the changes will be saved in fake home, which is the same when runningg with wine mode
+
 	# should delete the old symlink every time if symlink was created with absolute path, because appimage will generate different $APPDIR every time.
 	#[[ -d "$WINEPREFIX/drive_c/users/steamuser/Documents" ]] && rm -rf "$WINEPREFIX/drive_c/users/steamuser/Documents" || rm -f "$WINEPREFIX/drive_c/users/steamuser/Documents"
 	#ln -sfn "$MNT_HOMESTORGE/$FAKE_DOCUMENTS_DIR_NAME" "$WINEPREFIX/drive_c/users/steamuser/Documents"
@@ -307,11 +308,11 @@ function wine_restore_prefix(){
 	ln -sfnv ../../../../../../../../../../home/public_user/AppData/Roaming "$WINEPREFIX/drive_c/users/steamuser/AppData/Roaming"
 	
 
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "end <<<<<<<< [${FUNCNAME[0]}]"
+	echo "end >>>>>>>> [${FUNCNAME[0]}]" >&3
 }
 
 function wine_wait_shutdown(){
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "start >>>>>>>> [${FUNCNAME[0]}]"
+	echo "start >>>>>>>> [${FUNCNAME[0]}]" >&3
 
 	#"$HOME/$PROTON_DIR_FROM_HOME/proton" run wineboot -s
 
@@ -322,20 +323,28 @@ function wine_wait_shutdown(){
 	# NOTUSED: deirectly use wineserver instead of "proton run wineserver" because proton will exec wineserver in background
 	#"$HOME/$PROTON_DIR_FROM_HOME/proton" run wineserver -w
 	wineserver -w
+	if [[ $? -ne 0 ]];
+	then
+		echo "[$(basename "${BASH_SOURCE[0]}"):${FUNCNAME[0]}] ERROR: wineserver did not shutdown normally. exit code=$?" >&2
+		wineserver -k
+		#NOTUSED: should not exit here. it may skip atexit() and let unionfs remain in background
+		#exit
+	fi
 
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "end <<<<<<<< [${FUNCNAME[0]}]"
+	echo "end >>>>>>>> [${FUNCNAME[0]}]" >&3
 }
 
 function wine_patch_reg(){
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "start >>>>>>>> [${FUNCNAME[0]}]"
+	echo "start >>>>>>>> [${FUNCNAME[0]}]" >&3
 
-	[[ -z "$MNT_MYAPPSTORGE" ]] && echo "[wine_restore_prefix] ERROR:\$MNT_MYAPPSTORGE not set" >&2 && exit
+	[[ -z "$MNT_MYAPPSTORGE" ]] && echo "[$(basename "${BASH_SOURCE[0]}"):${FUNCNAME[0]}] ERROR: \$MNT_MYAPPSTORGE not set" >&2 && exit
 
 	# I tried to disable autostart winedbg via loading the .reg by regedit but failed.
 	# as a workaround I use winetricks to disable autostart debugger.
 	# TODO: seems the imported reg were effected in wow6432node instead of the correct reg path
+	# update on 2022/3/25: No need to disable autostart_winedbg now because I fixed trap-exit function. Now I can easily use <Ctrl-C> to stop the process even when wine crash.
 	#winetricks autostart_winedbg=disabled
-	"$WINETRICKS_BIN" autostart_winedbg=disabled >&3 2>&4
+	#"$WINETRICKS_BIN" autostart_winedbg=disabled >&3 2>&4
 
 	if [[ -n "$(ls "$MNT_MYAPPSTORGE"/myapp_patch_reg/*.reg 2>/dev/null )" ]];
 	then
@@ -357,16 +366,17 @@ function wine_patch_reg(){
 		done
 	fi
 
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "end <<<<<<<< [${FUNCNAME[0]}]"
+	echo "end >>>>>>>> [${FUNCNAME[0]}]" >&3
 }
 ##############################################
 
 
 ##############################################
 function wine_run_winetricks(){
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "start >>>>>>>> [${FUNCNAME[0]}]"
+	echo "start >>>>>>>> [${FUNCNAME[0]}]" >&3
 
 	echo "[${FUNCNAME[0]}:20%] prepare prefix"
+	# move the command to background then wait, so that I can use ctrl-C to interrupt wine if wine encounter crash
 	wine_restore_prefix >&3 2>&4 &
 	wait
 	#"$APPDIR"/usr/bin/winetricks sandbox	# this command run too slow
@@ -380,11 +390,11 @@ function wine_run_winetricks(){
 	#"$APPDIR"/usr/bin/winetricks "$@"
 	"$WINETRICKS_BIN" "$@" >&3 2>&4
 
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "end <<<<<<<< [${FUNCNAME[0]}]"
+	echo "end >>>>>>>> [${FUNCNAME[0]}]" >&3
 }
 
 function wine_run_exe(){
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "start >>>>>>>> [${FUNCNAME[0]}]"
+	echo "start >>>>>>>> [${FUNCNAME[0]}]" >&3
 
 	echo "[${FUNCNAME[0]}:20%] prepare prefix"
 	wine_restore_prefix >&3 2>&4 &
@@ -416,7 +426,7 @@ function wine_run_exe(){
 	#"$HOME/$PROTON_DIR_FROM_HOME/temprun.$WINEARCH.proton" run "${EXE_WROOT}:\\${EXE_WDIR}\\$EXENAME" "$@" >/dev/null 2>&1
 	"$HOME/$PROTON_DIR_FROM_HOME/proton" run "${EXE_WROOT}:\\${EXE_WDIR}\\$EXENAME" "$@" >&3 2>&4
 
-	[[ $MYAPPDEBUG -eq 1 ]] && echo "end <<<<<<<< [${FUNCNAME[0]}]"
+	echo "end >>>>>>>> [${FUNCNAME[0]}]" >&3
 }
 ##############################################
 
@@ -425,9 +435,9 @@ function wine_run_exe(){
 [[ "$0" == "${BASH_SOURCE[0]}" && $MYAPPDEBUG -eq 1 ]] && wine_test_env
 if [[ "$0" == "${BASH_SOURCE[0]}" ]];
 then
-	[[ -n $APPDIR ]] || echo "[AppRun:plugin_exeinfo] required \$APPDIR but it was not set"
-	[[ -n $APPIMAGE_CACHE_DIR ]] || echo "[AppRun:plugin_exeinfo] required \$APPIMAGE_CACHE_DIR but it was not set"
-	[[ -n $EXEINFO_GEN_METHOD ]] || echo "[AppRun:plugin_exeinfo] required \$EXEINFO_GEN_METHOD but it was not set"
+	[[ -n $APPDIR ]] || echo "[$(basename "${BASH_SOURCE[0]}")] required \$APPDIR but it was not set" >&2
+	[[ -n $APPIMAGE_CACHE_DIR ]] || echo "[$(basename "${BASH_SOURCE[0]}")] required \$APPIMAGE_CACHE_DIR but it was not set" >&2
+	[[ -n $EXEINFO_GEN_METHOD ]] || echo "[$(basename "${BASH_SOURCE[0]}")] required \$EXEINFO_GEN_METHOD but it was not set" >&2
 	[[ -n $APPDIR || -n $APPIMAGE_CACHE_DIR || -n $EXEINFO_GEN_METHOD ]] || exit
 fi
 wine_detect_winetricks
